use std::{
    collections::BTreeMap,
    error::Error,
    fmt, fs, io,
    path::{Path, PathBuf},
    sync::atomic::{AtomicU64, Ordering},
};

use crate::fakes::{
    CompareAndSwapError, ControlPlaneError, DeterministicClock, DeterministicIdGenerator,
    FakeControlPlaneClient, WorkspaceControlPlaneClient, WorkspaceRef,
};
use bowline_core::ids::{DeviceId, SnapshotId, WorkspaceId};

static NEXT_TEMP_WORKSPACE: AtomicU64 = AtomicU64::new(1);

#[derive(Debug)]
pub struct TempWorkspace {
    root: PathBuf,
}

impl TempWorkspace {
    pub fn new(name: &str) -> io::Result<Self> {
        let sequence = NEXT_TEMP_WORKSPACE.fetch_add(1, Ordering::Relaxed);
        let root = std::env::temp_dir().join(format!(
            "bowline-local-{}-{}-{}",
            std::process::id(),
            sanitize_path_part(name),
            sequence
        ));

        if root.exists() {
            fs::remove_dir_all(&root)?;
        }
        fs::create_dir_all(&root)?;

        Ok(Self { root })
    }

    pub fn root(&self) -> &Path {
        &self.root
    }

    pub fn create_project(&self, name: &str) -> io::Result<PathBuf> {
        let project_root = self.root.join(name);
        fs::create_dir_all(&project_root)?;
        Ok(project_root)
    }

    pub fn write_file(&self, relative_path: impl AsRef<Path>, bytes: &[u8]) -> io::Result<PathBuf> {
        let path = self.root.join(relative_path.as_ref());
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(&path, bytes)?;
        Ok(path)
    }

    pub fn write_project_file(
        &self,
        project: &str,
        relative_path: impl AsRef<Path>,
        bytes: &[u8],
    ) -> io::Result<PathBuf> {
        self.write_file(Path::new(project).join(relative_path.as_ref()), bytes)
    }

    pub fn create_git_repo(&self, project: &str) -> io::Result<PathBuf> {
        let git_root = self.root.join(project).join(".git");
        fs::create_dir_all(git_root.join("refs").join("heads"))?;
        fs::write(git_root.join("HEAD"), b"ref: refs/heads/main\n")?;
        fs::write(
            git_root.join("config"),
            b"[core]\n\trepositoryformatversion = 0\n",
        )?;
        Ok(git_root)
    }

    pub fn create_env_file(
        &self,
        project: &str,
        name: &str,
        contents: &[u8],
    ) -> io::Result<PathBuf> {
        self.write_project_file(project, name, contents)
    }

    pub fn create_generated_folder(&self, project: &str, name: &str) -> io::Result<PathBuf> {
        let generated_root = self.root.join(project).join(name);
        fs::create_dir_all(&generated_root)?;
        fs::write(generated_root.join(".generated"), b"generated by fixture\n")?;
        Ok(generated_root)
    }

    pub fn create_binary_file(
        &self,
        project: &str,
        relative_path: impl AsRef<Path>,
    ) -> io::Result<PathBuf> {
        self.write_project_file(
            project,
            relative_path,
            &[0x00, 0x9f, 0xff, 0x11, 0x7e, 0x42, 0x00],
        )
    }

    pub fn create_nested_repo(
        &self,
        project: &str,
        relative_path: impl AsRef<Path>,
    ) -> io::Result<PathBuf> {
        let nested_root = self.root.join(project).join(relative_path.as_ref());
        fs::create_dir_all(&nested_root)?;
        let nested_project = Path::new(project).join(relative_path.as_ref());
        self.create_git_repo(&nested_project.to_string_lossy())
    }

    #[cfg(unix)]
    pub fn create_symlink(
        &self,
        project: &str,
        link_path: impl AsRef<Path>,
        target: impl AsRef<Path>,
    ) -> io::Result<PathBuf> {
        use std::os::unix::fs::symlink;

        let link_path = self.root.join(project).join(link_path.as_ref());
        if let Some(parent) = link_path.parent() {
            fs::create_dir_all(parent)?;
        }
        symlink(target.as_ref(), &link_path)?;
        Ok(link_path)
    }

    #[cfg(not(unix))]
    pub fn create_symlink(
        &self,
        project: &str,
        link_path: impl AsRef<Path>,
        target: impl AsRef<Path>,
    ) -> io::Result<PathBuf> {
        self.write_project_file(
            project,
            link_path,
            target.as_ref().to_string_lossy().as_bytes(),
        )
    }

    pub fn mutation_detector(&self) -> io::Result<WorkspaceMutationDetector> {
        WorkspaceMutationDetector::new(&self.root)
    }
}

impl Drop for TempWorkspace {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.root);
    }
}

#[derive(Debug, Clone)]
pub struct WorkspaceMutationDetector {
    root: PathBuf,
    before: BTreeMap<PathBuf, EntryFingerprint>,
}

impl WorkspaceMutationDetector {
    pub fn new(root: impl Into<PathBuf>) -> io::Result<Self> {
        let root = root.into();
        let before = snapshot_tree(&root)?;
        Ok(Self { root, before })
    }

    pub fn assert_unchanged(&self) -> Result<(), WorkspaceMutationError> {
        let after = snapshot_tree(&self.root)?;
        let mutation = diff_snapshots(&self.before, &after);

        if mutation.is_empty() {
            Ok(())
        } else {
            Err(WorkspaceMutationError::Mutated(mutation))
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WorkspaceMutation {
    pub added: Vec<PathBuf>,
    pub removed: Vec<PathBuf>,
    pub changed: Vec<PathBuf>,
}

impl WorkspaceMutation {
    pub fn is_empty(&self) -> bool {
        self.added.is_empty() && self.removed.is_empty() && self.changed.is_empty()
    }
}

#[derive(Debug)]
pub enum WorkspaceMutationError {
    Io(io::Error),
    Mutated(WorkspaceMutation),
}

impl fmt::Display for WorkspaceMutationError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Io(error) => write!(formatter, "workspace mutation scan failed: {error}"),
            Self::Mutated(mutation) => write!(
                formatter,
                "workspace mutated: added={:?} removed={:?} changed={:?}",
                mutation.added, mutation.removed, mutation.changed
            ),
        }
    }
}

impl Error for WorkspaceMutationError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::Io(error) => Some(error),
            Self::Mutated(_) => None,
        }
    }
}

impl From<io::Error> for WorkspaceMutationError {
    fn from(error: io::Error) -> Self {
        Self::Io(error)
    }
}

#[derive(Debug)]
pub struct TwoDeviceLocalHarness {
    pub workspace_id: String,
    pub control_plane: FakeControlPlaneClient,
    pub device_a: FakeDevice,
    pub device_b: FakeDevice,
}

impl TwoDeviceLocalHarness {
    pub fn new() -> io::Result<Self> {
        let clock = DeterministicClock::default();
        let ids = DeterministicIdGenerator::new("bowline");
        let control_plane = FakeControlPlaneClient::new(clock, ids.clone());
        let workspace_id = ids.next_id("workspace");
        control_plane.create_workspace(&workspace_id);

        let device_a = FakeDevice::new(
            ids.next_id("device"),
            TempWorkspace::new("device-a")?,
            control_plane.clone(),
        );
        let device_b = FakeDevice::new(
            ids.next_id("device"),
            TempWorkspace::new("device-b")?,
            control_plane.clone(),
        );

        Ok(Self {
            workspace_id,
            control_plane,
            device_a,
            device_b,
        })
    }
}

#[derive(Debug)]
pub struct FakeDevice {
    pub device_id: String,
    pub root: TempWorkspace,
    control_plane: FakeControlPlaneClient,
    online: bool,
}

impl FakeDevice {
    pub fn new(
        device_id: impl Into<String>,
        root: TempWorkspace,
        control_plane: FakeControlPlaneClient,
    ) -> Self {
        Self {
            device_id: device_id.into(),
            root,
            control_plane,
            online: true,
        }
    }

    pub fn set_online(&mut self, online: bool) {
        self.online = online;
    }

    pub fn is_online(&self) -> bool {
        self.online
    }

    pub fn observe_workspace_ref(
        &self,
        workspace_id: &str,
    ) -> Result<WorkspaceRef, FakeDeviceError> {
        self.require_online()?;
        self.control_plane
            .observe_workspace_ref(&WorkspaceId::new(workspace_id))
            .map_err(FakeDeviceError::ControlPlane)?
            .ok_or_else(|| FakeDeviceError::WorkspaceMissing {
                workspace_id: workspace_id.to_string(),
            })
    }

    pub fn advance_workspace_ref(
        &self,
        workspace_id: &str,
        expected_version: u64,
        snapshot_id: &str,
    ) -> Result<WorkspaceRef, FakeDeviceError> {
        self.require_online()?;
        self.control_plane
            .compare_and_swap_workspace_ref(
                &WorkspaceId::new(workspace_id),
                expected_version,
                &SnapshotId::new(snapshot_id),
                &DeviceId::new(&self.device_id),
            )
            .map_err(FakeDeviceError::CompareAndSwap)
    }

    fn require_online(&self) -> Result<(), FakeDeviceError> {
        if self.online {
            Ok(())
        } else {
            Err(FakeDeviceError::Offline {
                device_id: self.device_id.clone(),
            })
        }
    }
}

#[derive(Debug, PartialEq, Eq)]
pub enum FakeDeviceError {
    ControlPlane(ControlPlaneError),
    Offline { device_id: String },
    WorkspaceMissing { workspace_id: String },
    CompareAndSwap(CompareAndSwapError),
}

impl fmt::Display for FakeDeviceError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::ControlPlane(error) => error.fmt(formatter),
            Self::Offline { device_id } => write!(formatter, "device `{device_id}` is offline"),
            Self::WorkspaceMissing { workspace_id } => {
                write!(formatter, "workspace `{workspace_id}` does not exist")
            }
            Self::CompareAndSwap(error) => error.fmt(formatter),
        }
    }
}

impl Error for FakeDeviceError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::ControlPlane(error) => Some(error),
            Self::CompareAndSwap(error) => Some(error),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum EntryFingerprint {
    Directory,
    File { len: u64, hash: u64 },
    Symlink { target: PathBuf },
}

fn snapshot_tree(root: &Path) -> io::Result<BTreeMap<PathBuf, EntryFingerprint>> {
    let mut snapshot = BTreeMap::new();
    visit_tree(root, root, &mut snapshot)?;
    Ok(snapshot)
}

fn visit_tree(
    root: &Path,
    directory: &Path,
    snapshot: &mut BTreeMap<PathBuf, EntryFingerprint>,
) -> io::Result<()> {
    let mut entries = fs::read_dir(directory)?.collect::<Result<Vec<_>, _>>()?;
    entries.sort_by_key(|entry| entry.file_name());

    for entry in entries {
        let path = entry.path();
        let metadata = fs::symlink_metadata(&path)?;
        let relative_path = path.strip_prefix(root).map_err(|error| {
            io::Error::new(
                io::ErrorKind::InvalidData,
                format!(
                    "walked entry outside root `{}` relative to `{}`: {error}",
                    path.display(),
                    root.display()
                ),
            )
        })?;
        let relative_path = relative_path.to_path_buf();
        let file_type = metadata.file_type();

        if file_type.is_symlink() {
            snapshot.insert(
                relative_path,
                EntryFingerprint::Symlink {
                    target: fs::read_link(&path)?,
                },
            );
        } else if file_type.is_dir() {
            snapshot.insert(relative_path.clone(), EntryFingerprint::Directory);
            visit_tree(root, &path, snapshot)?;
        } else if file_type.is_file() {
            snapshot.insert(
                relative_path,
                EntryFingerprint::File {
                    len: metadata.len(),
                    hash: hash_file(&path)?,
                },
            );
        }
    }

    Ok(())
}

fn diff_snapshots(
    before: &BTreeMap<PathBuf, EntryFingerprint>,
    after: &BTreeMap<PathBuf, EntryFingerprint>,
) -> WorkspaceMutation {
    let added = after
        .keys()
        .filter(|path| !before.contains_key(*path))
        .cloned()
        .collect();
    let removed = before
        .keys()
        .filter(|path| !after.contains_key(*path))
        .cloned()
        .collect();
    let changed = before
        .iter()
        .filter_map(|(path, before_fingerprint)| {
            after
                .get(path)
                .filter(|after_fingerprint| *after_fingerprint != before_fingerprint)
                .map(|_| path.clone())
        })
        .collect();

    WorkspaceMutation {
        added,
        removed,
        changed,
    }
}

fn hash_file(path: &Path) -> io::Result<u64> {
    let bytes = fs::read(path)?;
    let mut hash = 0xcbf29ce484222325u64;
    for byte in bytes {
        hash ^= u64::from(byte);
        hash = hash.wrapping_mul(0x100000001b3);
    }
    Ok(hash)
}

fn sanitize_path_part(value: &str) -> String {
    let mut sanitized = String::new();

    for character in value.chars() {
        if character.is_ascii_alphanumeric() || character == '-' || character == '_' {
            sanitized.push(character.to_ascii_lowercase());
        } else {
            sanitized.push('-');
        }
    }

    if sanitized.is_empty() {
        "workspace".to_string()
    } else {
        sanitized
    }
}

#[cfg(test)]
mod tests {
    use super::{FakeDeviceError, TempWorkspace, TwoDeviceLocalHarness, WorkspaceMutationError};

    #[test]
    fn temp_workspace_can_create_code_like_fixture() {
        let workspace = TempWorkspace::new("fixture").expect("temp workspace");
        workspace.create_project("acme-web").expect("project");
        workspace
            .write_project_file("acme-web", "src/main.rs", b"fn main() {}\n")
            .expect("source");
        workspace
            .create_git_repo("acme-web")
            .expect("git metadata fixture");
        workspace
            .create_env_file("acme-web", ".env", b"API_TOKEN=local\n")
            .expect("env fixture");
        workspace
            .create_generated_folder("acme-web", "target")
            .expect("generated fixture");
        workspace
            .create_binary_file("acme-web", "assets/logo.bin")
            .expect("binary fixture");
        workspace
            .create_nested_repo("acme-web", "vendor/dep")
            .expect("nested repo fixture");

        assert!(workspace.root().join("acme-web/src/main.rs").exists());
        assert!(workspace.root().join("acme-web/.git/HEAD").exists());
        assert!(
            workspace
                .root()
                .join("acme-web/vendor/dep/.git/HEAD")
                .exists()
        );
    }

    #[test]
    fn mutation_detector_catches_unexpected_writes() {
        let workspace = TempWorkspace::new("mutation").expect("temp workspace");
        workspace
            .write_file("project/src/lib.rs", b"pub fn ok() {}\n")
            .expect("source");
        let detector = workspace.mutation_detector().expect("detector");

        workspace
            .write_file("project/src/lib.rs", b"pub fn changed() {}\n")
            .expect("changed source");
        let error = detector
            .assert_unchanged()
            .expect_err("mutation should be detected");

        assert!(matches!(
            error,
            WorkspaceMutationError::Mutated(mutation)
                if mutation.changed == vec![std::path::PathBuf::from("project/src/lib.rs")]
        ));
    }

    #[test]
    fn two_fake_devices_observe_and_advance_one_workspace_ref() {
        let harness = TwoDeviceLocalHarness::new().expect("two-device harness");
        let initial_ref = harness
            .device_a
            .observe_workspace_ref(&harness.workspace_id)
            .expect("device A observes ref");

        let advanced_ref = harness
            .device_a
            .advance_workspace_ref(&harness.workspace_id, initial_ref.version, "snapshot-a")
            .expect("device A advances ref");
        let observed_by_b = harness
            .device_b
            .observe_workspace_ref(&harness.workspace_id)
            .expect("device B observes advanced ref");

        assert_eq!(advanced_ref, observed_by_b);
        assert_eq!(
            advanced_ref.updated_by_device_id,
            Some(bowline_core::ids::DeviceId::new(harness.device_a.device_id,))
        );
    }

    #[test]
    fn fake_device_offline_toggle_blocks_control_plane_access() {
        let mut harness = TwoDeviceLocalHarness::new().expect("two-device harness");
        harness.device_b.set_online(false);

        let error = harness
            .device_b
            .observe_workspace_ref(&harness.workspace_id)
            .expect_err("offline device cannot observe remote ref");

        assert_eq!(
            error,
            FakeDeviceError::Offline {
                device_id: harness.device_b.device_id,
            }
        );
    }
}
