use super::*;

pub(super) const DAEMON_COMMAND_REGISTRY: &[CommandSpec] = &[
    CommandSpec {
        group: "Daemon",
        name: "daemon start",
        summary: "Start the local daemon process.",
        usage: "bowline daemon start [--json]",
        options: &[SOCKET_OPTION, GLOBAL_JSON_OPTION],
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "DaemonCommandOutput",
        side_effect_level: "daemon-mutation",
        supports_json: true,
        supports_dry_run: false,
        bounded_output: None,
        related_commands: &["daemon status"],
    },
    CommandSpec {
        group: "Daemon",
        name: "daemon stop",
        summary: "Stop the local daemon process.",
        usage: "bowline daemon stop [--json]",
        options: &[SOCKET_OPTION, GLOBAL_JSON_OPTION],
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "DaemonCommandOutput",
        side_effect_level: "daemon-mutation",
        supports_json: true,
        supports_dry_run: false,
        bounded_output: None,
        related_commands: &["daemon status"],
    },
    CommandSpec {
        group: "Daemon",
        name: "daemon status",
        summary: "Inspect daemon process and service state.",
        usage: "bowline daemon status [--json]",
        options: &[SOCKET_OPTION, GLOBAL_JSON_OPTION],
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "DaemonStatusOutput",
        side_effect_level: "read",
        supports_json: true,
        supports_dry_run: false,
        bounded_output: None,
        related_commands: &["daemon start", "daemon install"],
    },
    CommandSpec {
        group: "Daemon",
        name: "daemon install",
        summary: "Install or update the OS service for the daemon.",
        usage: "bowline daemon install [--json] [--dry-run]",
        options: &[SOCKET_OPTION, GLOBAL_JSON_OPTION, DRY_RUN_OPTION],
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "DaemonServiceOutput",
        side_effect_level: "service-mutation",
        supports_json: true,
        supports_dry_run: true,
        bounded_output: None,
        related_commands: &["daemon restart", "daemon uninstall"],
    },
    CommandSpec {
        group: "Daemon",
        name: "daemon restart",
        summary: "Restart the installed daemon service.",
        usage: "bowline daemon restart [--json] [--dry-run]",
        options: &[GLOBAL_JSON_OPTION, DRY_RUN_OPTION],
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "DaemonServiceOutput",
        side_effect_level: "service-mutation",
        supports_json: true,
        supports_dry_run: true,
        bounded_output: None,
        related_commands: &["daemon install"],
    },
    CommandSpec {
        group: "Daemon",
        name: "daemon uninstall",
        summary: "Uninstall the daemon OS service.",
        usage: "bowline daemon uninstall [--json] [--dry-run]",
        options: &[GLOBAL_JSON_OPTION, DRY_RUN_OPTION],
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "DaemonServiceOutput",
        side_effect_level: "service-mutation",
        supports_json: true,
        supports_dry_run: true,
        bounded_output: None,
        related_commands: &["daemon install"],
    },
];
