use super::*;

pub(super) const COMMAND_REGISTRY: &[CommandSpec] = &[
    CommandSpec {
        group: "Discovery",
        name: "help",
        summary: "Show human or JSON help for every CLI command.",
        usage: "bowline help [topic] [--json]",
        options: &[GLOBAL_JSON_OPTION],
        positionals: HELP_POSITIONALS,
        examples: &[ExampleSpec {
            command: "bowline help agent start --json",
            summary: "Inspect nested help for agent lease creation.",
        }],
        json_output_type: "HelpCommandOutput",
        side_effect_level: "none",
        supports_json: true,
        supports_dry_run: false,
        bounded_output: None,
        related_commands: &["contract", "version"],
    },
    CommandSpec {
        group: "Discovery",
        name: "version",
        summary: "Print CLI version and protocol compatibility.",
        usage: "bowline version [--json]",
        options: &[GLOBAL_JSON_OPTION],
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "VersionCommandOutput",
        side_effect_level: "none",
        supports_json: true,
        supports_dry_run: false,
        bounded_output: None,
        related_commands: &["contract"],
    },
    CommandSpec {
        group: "Discovery",
        name: "contract",
        summary: "Print the machine-readable CLI command and output contract.",
        usage: "bowline contract [topic] [--summary] [--json]",
        options: &[CONTRACT_SUMMARY_OPTION, GLOBAL_JSON_OPTION],
        positionals: HELP_POSITIONALS,
        examples: &[
            ExampleSpec {
                command: "bowline contract --summary --json",
                summary: "Print the compact command discovery index.",
            },
            ExampleSpec {
                command: "bowline contract work diff --json",
                summary: "Fetch one full command descriptor.",
            },
        ],
        json_output_type: "ContractCommandOutput",
        side_effect_level: "none",
        supports_json: true,
        supports_dry_run: false,
        bounded_output: None,
        related_commands: &["help", "version"],
    },
    CommandSpec {
        group: "Discovery",
        name: "mcp",
        summary: "Run Bowline's MCP stdio agent tool server.",
        usage: "bowline mcp [--lease <id>] [--token-file <path>] [--socket <path>]",
        options: &[
            OptionSpec {
                name: "--lease",
                value_name: Some("id"),
                summary: "Bind every tool call to this agent lease. Falls back to BOWLINE_LEASE_ID.",
                required: false,
                repeatable: false,
            },
            OptionSpec {
                name: "--token-file",
                value_name: Some("path"),
                summary: "Use this lease-scoped MCP token file. Falls back to BOWLINE_MCP_TOKEN_FILE.",
                required: false,
                repeatable: false,
            },
            SOCKET_OPTION,
        ],
        positionals: NO_POSITIONALS,
        examples: &[ExampleSpec {
            command: "bowline mcp --lease lease_123 --token-file ~/.local/state/bowline/mcp/token",
            summary: "Start a lease-bound MCP stdio server.",
        }],
        json_output_type: "none",
        side_effect_level: "none",
        supports_json: false,
        supports_dry_run: false,
        bounded_output: None,
        related_commands: &["agent context"],
    },
    CommandSpec {
        group: "Workspace",
        name: "update",
        summary: "Check for or install the latest Bowline release.",
        usage: "bowline update [--check] [--version <version>] [--json]",
        options: &[
            OptionSpec {
                name: "--check",
                value_name: None,
                summary: "Only check whether an update is available.",
                required: false,
                repeatable: false,
            },
            OptionSpec {
                name: "--version",
                value_name: Some("version"),
                summary: "Install or check a specific release version.",
                required: false,
                repeatable: false,
            },
            GLOBAL_JSON_OPTION,
        ],
        positionals: NO_POSITIONALS,
        examples: &[ExampleSpec {
            command: "bowline update --check --json",
            summary: "Check the install host release manifest.",
        }],
        json_output_type: "UpdateCommandOutput",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: false,
        bounded_output: None,
        related_commands: &["version", "status"],
    },
    CommandSpec {
        group: "Workspace",
        name: "login",
        summary: "Sign in and onboard this machine with the default ~/Code workspace.",
        usage: "bowline login [--headless] [--no-poll] [--json]",
        options: &[
            OptionSpec {
                name: "--headless",
                value_name: None,
                summary: "Start login without interactive polling.",
                required: false,
                repeatable: false,
            },
            OptionSpec {
                name: "--no-poll",
                value_name: None,
                summary: "Print the pending login instructions and exit without polling.",
                required: false,
                repeatable: false,
            },
            GLOBAL_JSON_OPTION,
        ],
        positionals: NO_POSITIONALS,
        examples: &[ExampleSpec {
            command: "bowline setup --root ~/Projects",
            summary: "Use an explicit workspace root instead of ~/Code.",
        }],
        json_output_type: "LoginCommandOutput | SetupCommandOutput",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: false,
        bounded_output: None,
        related_commands: &["setup", "logout"],
    },
    CommandSpec {
        group: "Workspace",
        name: "logout",
        summary: "Clear the saved local account session without removing device trust.",
        usage: "bowline logout [--json]",
        options: &[GLOBAL_JSON_OPTION],
        positionals: NO_POSITIONALS,
        examples: &[ExampleSpec {
            command: "bowline logout",
            summary: "Sign this machine out of the current account session.",
        }],
        json_output_type: "LogoutCommandOutput",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: false,
        bounded_output: None,
        related_commands: &["login", "status"],
    },
    CommandSpec {
        group: "Workspace",
        name: "status",
        summary: "Inspect workspace, sync, and safe next actions.",
        usage: "bowline status [--root <path>] [--project <path>] [--watch] [--all] [--json]",
        options: &[
            OPTIONAL_ROOT_OPTION,
            PROJECT_OPTION,
            OptionSpec {
                name: "--watch",
                value_name: None,
                summary: "Stream status frames.",
                required: false,
                repeatable: false,
            },
            OptionSpec {
                name: "--all",
                value_name: None,
                summary: "Include retained and archived work status.",
                required: false,
                repeatable: false,
            },
            GLOBAL_JSON_OPTION,
        ],
        positionals: NO_POSITIONALS,
        examples: &[ExampleSpec {
            command: "bowline status --root ~/Code --json",
            summary: "Parse the current workspace status.",
        }],
        json_output_type: "StatusCommandOutput",
        side_effect_level: "read",
        supports_json: true,
        supports_dry_run: false,
        bounded_output: None,
        related_commands: &["events", "diagnostics collect"],
    },
    CommandSpec {
        group: "Workspace",
        name: "setup",
        summary: "Set up this machine or prepare one project for Bowline.",
        usage: "bowline setup [--root <path>] [--socket <path>] [--json] | bowline setup <path> [--yes] [--socket <path>] [--json]",
        options: &[
            OPTIONAL_ROOT_OPTION,
            OptionSpec {
                name: "--yes",
                value_name: None,
                summary: "Approve required project setup changes when a path is provided.",
                required: false,
                repeatable: false,
            },
            SOCKET_OPTION,
            GLOBAL_JSON_OPTION,
        ],
        positionals: OPTIONAL_PROJECT_POSITIONAL,
        examples: &[
            ExampleSpec {
                command: "bowline setup",
                summary: "Onboard this machine with the default workspace root.",
            },
            ExampleSpec {
                command: "bowline setup . --json",
                summary: "Prepare the current project and emit setup receipts.",
            },
        ],
        json_output_type: "SetupCommandOutput | SetupProjectOutput",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: false,
        bounded_output: None,
        related_commands: &["login", "status"],
    },
    CommandSpec {
        group: "Workspace",
        name: "events",
        summary: "List recent workspace events.",
        usage: "bowline events [--root <path>] [--project <path>] [--limit <n>] [--json|--human|--quiet]",
        options: &[
            OPTIONAL_ROOT_OPTION,
            PROJECT_OPTION,
            LIMIT_OPTION,
            GLOBAL_JSON_OPTION,
            QUIET_OPTION,
        ],
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "EventsCommandOutput",
        side_effect_level: "read",
        supports_json: true,
        supports_dry_run: false,
        bounded_output: None,
        related_commands: &["status"],
    },
    CommandSpec {
        group: "Workspace",
        name: "history",
        summary: "List project restore points and path history.",
        usage: "bowline history [path] [--limit <n>] [--cursor <cursor>] [--since <time>] [--until <time>] [--json|--human|--quiet]",
        options: HISTORY_OPTIONS,
        positionals: HISTORY_POSITIONALS,
        examples: HISTORY_EXAMPLES,
        json_output_type: "HistoryCommandOutput",
        side_effect_level: "read",
        supports_json: true,
        supports_dry_run: false,
        bounded_output: Some(HISTORY_BOUND),
        related_commands: &["events", "work create"],
    },
    CommandSpec {
        group: "Workspace",
        name: "resolve",
        summary: "Resolve conflicts or produce agent-ready conflict context.",
        usage: "bowline resolve [path] [--tui] [--copy-prompt] [--diff <conflict>] [--agent <agent>] [--accept <conflict>|--reject <conflict>] [--json]",
        options: RESOLVE_OPTIONS,
        positionals: OPTIONAL_PROJECT_POSITIONAL,
        examples: EMPTY_EXAMPLES,
        json_output_type: "ResolveCommandOutput",
        side_effect_level: "read",
        supports_json: true,
        supports_dry_run: false,
        bounded_output: None,
        related_commands: &["status"],
    },
    CommandSpec {
        group: "Workspace",
        name: "tui",
        summary: "Open the terminal workspace UI.",
        usage: "bowline tui [--root <path>] [--project <path>] [--socket <path>]",
        options: &[OPTIONAL_ROOT_OPTION, PROJECT_OPTION, SOCKET_OPTION],
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "none",
        side_effect_level: "interactive",
        supports_json: false,
        supports_dry_run: false,
        bounded_output: None,
        related_commands: &["status"],
    },
    CommandSpec {
        group: "Workspace",
        name: "forget-local",
        summary: "Remove one materialized project from this device after preview.",
        usage: "bowline forget-local <project> [--yes] [--json] [--dry-run]",
        options: &[
            OptionSpec {
                name: "--yes",
                value_name: None,
                summary: "Remove local bytes after reviewing the preview.",
                required: false,
                repeatable: false,
            },
            GLOBAL_JSON_OPTION,
            DRY_RUN_OPTION,
        ],
        positionals: REQUIRED_PROJECT_POSITIONAL,
        examples: &[ExampleSpec {
            command: "bowline forget-local apps/web --dry-run",
            summary: "Preview local bytes that would be removed on this device.",
        }],
        json_output_type: "NamespaceLifecycleCommandOutput",
        side_effect_level: "local-filesystem-delete",
        supports_json: true,
        supports_dry_run: true,
        bounded_output: None,
        related_commands: &["setup", "archive", "purge"],
    },
    CommandSpec {
        group: "Workspace",
        name: "archive",
        summary: "Hide one project from default namespace views without deleting local bytes.",
        usage: "bowline archive <project> [--restore] [--json] [--dry-run]",
        options: &[
            OptionSpec {
                name: "--restore",
                value_name: None,
                summary: "Restore an archived project to active namespace views.",
                required: false,
                repeatable: false,
            },
            GLOBAL_JSON_OPTION,
            DRY_RUN_OPTION,
        ],
        positionals: REQUIRED_PROJECT_POSITIONAL,
        examples: &[ExampleSpec {
            command: "bowline archive apps/web --dry-run",
            summary: "Preview the archive transition.",
        }],
        json_output_type: "NamespaceLifecycleCommandOutput",
        side_effect_level: "workspace-metadata",
        supports_json: true,
        supports_dry_run: true,
        bounded_output: None,
        related_commands: &["forget-local", "purge", "status"],
    },
    CommandSpec {
        group: "Workspace",
        name: "purge",
        summary: "Schedule remote destruction for an archived project after a grace window.",
        usage: "bowline purge <project> [--grace <days>|--cancel] [--json] [--dry-run]",
        options: &[
            OptionSpec {
                name: "--grace",
                value_name: Some("days"),
                summary: "Grace period before remote objects become collectible; allowed range is 1-90 days.",
                required: false,
                repeatable: false,
            },
            OptionSpec {
                name: "--cancel",
                value_name: None,
                summary: "Cancel a purge-pending project and keep it archived.",
                required: false,
                repeatable: false,
            },
            GLOBAL_JSON_OPTION,
            DRY_RUN_OPTION,
        ],
        positionals: REQUIRED_PROJECT_POSITIONAL,
        examples: &[ExampleSpec {
            command: "bowline purge apps/web --dry-run",
            summary: "Preview the remote-retention impact before scheduling purge.",
        }],
        json_output_type: "NamespaceLifecycleCommandOutput",
        side_effect_level: "remote-destruction-scheduled",
        supports_json: true,
        supports_dry_run: true,
        bounded_output: None,
        related_commands: &["archive", "forget-local", "status"],
    },
    CommandSpec {
        group: "Trust",
        name: "device approve",
        summary: "Approve a pending device trust request.",
        usage: "bowline device approve [--root <path>] ((--request <id>|--code <short-code>)|--merge-plugin --id <id> --plugin-version <version> --digest <digest> [--matcher-version <version>] [--validator-version <version>]) [--yes] [--json] [--dry-run]",
        options: &[
            OPTIONAL_ROOT_OPTION,
            REQUEST_OPTION,
            CODE_OPTION,
            OptionSpec {
                name: "--merge-plugin",
                value_name: None,
                summary: "Approve a declared merge plugin instead of a device request.",
                required: false,
                repeatable: false,
            },
            OptionSpec {
                name: "--id",
                value_name: Some("id"),
                summary: "Declared merge plugin id.",
                required: false,
                repeatable: false,
            },
            OptionSpec {
                name: "--plugin-version",
                value_name: Some("version"),
                summary: "Declared merge plugin semantic version.",
                required: false,
                repeatable: false,
            },
            OptionSpec {
                name: "--digest",
                value_name: Some("digest"),
                summary: "Expected digest of the merge plugin module.",
                required: false,
                repeatable: false,
            },
            OptionSpec {
                name: "--matcher-version",
                value_name: Some("version"),
                summary: "Expected policy-bound matcher contract version.",
                required: false,
                repeatable: false,
            },
            OptionSpec {
                name: "--validator-version",
                value_name: Some("version"),
                summary: "Expected merge plugin validator version.",
                required: false,
                repeatable: false,
            },
            OptionSpec {
                name: "--yes",
                value_name: None,
                summary: "Approve without an interactive prompt.",
                required: false,
                repeatable: false,
            },
            GLOBAL_JSON_OPTION,
            DRY_RUN_OPTION,
        ],
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "DevicesCommandOutput",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: true,
        bounded_output: None,
        related_commands: &["device deny", "device revoke", "device list"],
    },
    CommandSpec {
        group: "Trust",
        name: "device deny",
        summary: "Deny a pending device trust request.",
        usage: "bowline device deny [--root <path>] (--request <id>|--code <short-code>) [--json] [--dry-run]",
        options: &[
            OPTIONAL_ROOT_OPTION,
            REQUEST_OPTION,
            CODE_OPTION,
            GLOBAL_JSON_OPTION,
            DRY_RUN_OPTION,
        ],
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "DevicesCommandOutput",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: true,
        bounded_output: None,
        related_commands: &["device approve", "device revoke", "device list"],
    },
    CommandSpec {
        group: "Trust",
        name: "device revoke",
        summary: "Revoke a trusted device.",
        usage: "bowline device revoke [--root <path>] --device <id> [--json] [--dry-run]",
        options: &[
            OPTIONAL_ROOT_OPTION,
            DEVICE_OPTION,
            GLOBAL_JSON_OPTION,
            DRY_RUN_OPTION,
        ],
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "DevicesCommandOutput",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: true,
        bounded_output: None,
        related_commands: &["device approve", "device deny", "device list"],
    },
    CommandSpec {
        group: "Trust",
        name: "recover",
        summary: "Manage recovery keys and recovery-based device grants.",
        usage: "bowline recover <status|create|verify <id>|rotate|revoke <id>|use <id>> [--json] [--dry-run]",
        options: &[GLOBAL_JSON_OPTION, DRY_RUN_OPTION],
        positionals: RECOVERY_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "RecoveryCommandOutput",
        side_effect_level: "mixed",
        supports_json: true,
        supports_dry_run: true,
        bounded_output: None,
        related_commands: &["device approve"],
    },
    CommandSpec {
        group: "Trust",
        name: "device list",
        summary: "List local device records.",
        usage: "bowline device list [--root <path>] [--json|--human|--quiet]",
        options: &[OPTIONAL_ROOT_OPTION, GLOBAL_JSON_OPTION, QUIET_OPTION],
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "DevicesCommandOutput",
        side_effect_level: "read",
        supports_json: true,
        supports_dry_run: false,
        bounded_output: None,
        related_commands: &["device approve", "device revoke", "device request"],
    },
    CommandSpec {
        group: "Trust",
        name: "device request",
        summary: "Raise a device approval request for this machine.",
        usage: "bowline device request [--root <path>] [--json]",
        options: &[OPTIONAL_ROOT_OPTION, GLOBAL_JSON_OPTION],
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "DevicesCommandOutput",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: false,
        bounded_output: None,
        related_commands: &["device accept", "device approve", "device list"],
    },
    CommandSpec {
        group: "Trust",
        name: "device accept",
        summary: "Accept an encrypted device grant for this machine.",
        usage: "bowline device accept [--root <path>] --request <id> [--json]",
        options: &[OPTIONAL_ROOT_OPTION, REQUEST_OPTION, GLOBAL_JSON_OPTION],
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "DevicesCommandOutput",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: false,
        bounded_output: None,
        related_commands: &["device request", "device approve", "device list"],
    },
    CommandSpec {
        group: "Remote",
        name: "connect",
        summary: "Inbound SSH: install, trust, and hand off an agent on a machine you own.",
        usage: "bowline connect <host> [--root <path>] [--binary <path>] [--project <project> --task <task> --agent <agent>] [--json] [--dry-run]",
        options: CONNECT_OPTIONS,
        positionals: REQUIRED_TARGET_POSITIONAL,
        examples: EMPTY_EXAMPLES,
        json_output_type: "BootstrapSshCommandOutput",
        side_effect_level: "remote-mutation",
        supports_json: true,
        supports_dry_run: true,
        bounded_output: None,
        related_commands: &["agent start", "lease join"],
    },
    CommandSpec {
        group: "Remote",
        name: "handoff",
        summary: "Move the latest Codex or Claude session to a trusted target and resume it in tmux.",
        usage: "bowline handoff <target> [--agent codex|claude] [--session <id-or-path>] [--prompt <text>|--prompt-file <path>] [--project <path>] [--json] [--dry-run]",
        options: HANDOFF_OPTIONS,
        positionals: REQUIRED_TARGET_POSITIONAL,
        examples: &[
            ExampleSpec {
                command: "bowline handoff linux-home",
                summary: "Send the newest supported local agent session to linux-home.",
            },
            ExampleSpec {
                command: "bowline handoff linux-home --agent claude --prompt-file prompt.md",
                summary: "Start a fresh Claude session on the target from a protected prompt file.",
            },
        ],
        json_output_type: "HandoffCommandOutput",
        side_effect_level: "remote-mutation",
        supports_json: true,
        supports_dry_run: true,
        bounded_output: None,
        related_commands: &["connect", "agent start"],
    },
    CommandSpec {
        group: "Agent",
        name: "agent start",
        summary: "Start a local direct-write agent lease, optionally using a work view or remote host.",
        usage: "bowline agent start [project] --task <task> [--base <base>] [--work-view] [--force-stale] [--on <authorized-device>] [--remote <runtime>] [--remote-root <path>] [--json] [--dry-run]",
        options: &[
            OptionSpec {
                name: "--task",
                value_name: Some("task"),
                summary: "Task description for the lease.",
                required: true,
                repeatable: false,
            },
            OptionSpec {
                name: "--base",
                value_name: Some("base"),
                summary: "Lease base, such as latest-workspace or latest:main.",
                required: false,
                repeatable: false,
            },
            OptionSpec {
                name: "--work-view",
                value_name: None,
                summary: "Write through an isolated work view.",
                required: false,
                repeatable: false,
            },
            OptionSpec {
                name: "--force-stale",
                value_name: None,
                summary: "Start anyway when the local freshness guardian sees a stale base.",
                required: false,
                repeatable: false,
            },
            OptionSpec {
                name: "--on",
                value_name: Some("authorized-device"),
                summary: "Dispatch the lease to an authorized device; unknown hosts use remote bootstrap.",
                required: false,
                repeatable: false,
            },
            OptionSpec {
                name: "--remote",
                value_name: Some("runtime"),
                summary: "Mint a lease-scoped bootstrap token for an outbound agent runtime.",
                required: false,
                repeatable: false,
            },
            OptionSpec {
                name: "--remote-root",
                value_name: Some("path"),
                summary: "Remote workspace root for the outbound runtime.",
                required: false,
                repeatable: false,
            },
            GLOBAL_JSON_OPTION,
            DRY_RUN_OPTION,
        ],
        positionals: OPTIONAL_PROJECT_POSITIONAL,
        examples: EMPTY_EXAMPLES,
        json_output_type: "AgentLeaseCreateCommandOutput",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: true,
        bounded_output: None,
        related_commands: &["connect", "lease join", "agent context"],
    },
    CommandSpec {
        group: "Agent",
        name: "agent context",
        summary: "Return full context for an agent lease.",
        usage: "bowline agent context --lease <id> [--json]",
        options: &[LEASE_ID_OPTION, GLOBAL_JSON_OPTION],
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "AgentContextCommandOutput",
        side_effect_level: "read",
        supports_json: true,
        supports_dry_run: false,
        bounded_output: None,
        related_commands: &["agent prompt"],
    },
    CommandSpec {
        group: "Agent",
        name: "agent prompt",
        summary: "Return launch prompt text for an agent lease.",
        usage: "bowline agent prompt --lease <id> [--json]",
        options: &[LEASE_ID_OPTION, GLOBAL_JSON_OPTION],
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "AgentPromptCommandOutput",
        side_effect_level: "read",
        supports_json: true,
        supports_dry_run: false,
        bounded_output: None,
        related_commands: &["agent context"],
    },
    CommandSpec {
        group: "Agent",
        name: "agent complete",
        summary: "Mark an agent session finished without applying or publishing its work.",
        usage: "bowline agent complete --lease <id> [--json] [--dry-run]",
        options: &[LEASE_ID_OPTION, GLOBAL_JSON_OPTION, DRY_RUN_OPTION],
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "AgentCompleteCommandOutput",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: true,
        bounded_output: None,
        related_commands: &["agent context", "work review", "work accept"],
    },
    CommandSpec {
        group: "Agent",
        name: "agent cancel",
        summary: "Cancel an agent session and revoke all lease authority.",
        usage: "bowline agent cancel --lease <id> [--json] [--dry-run]",
        options: &[LEASE_ID_OPTION, GLOBAL_JSON_OPTION, DRY_RUN_OPTION],
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "AgentLeaseUpdateCommandOutput",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: true,
        bounded_output: None,
        related_commands: &["agent context", "agent start"],
    },
    CommandSpec {
        group: "Agent",
        name: "agent extend",
        summary: "Extend an open agent lease to a bounded deadline.",
        usage: "bowline agent extend --lease <id> --hours <1..168> [--json] [--dry-run]",
        options: &[
            LEASE_ID_OPTION,
            OptionSpec {
                name: "--hours",
                value_name: Some("1..168"),
                summary: "Keep the lease valid for at least this many hours from now.",
                required: true,
                repeatable: false,
            },
            GLOBAL_JSON_OPTION,
            DRY_RUN_OPTION,
        ],
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "AgentLeaseUpdateCommandOutput",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: true,
        bounded_output: None,
        related_commands: &["agent context", "agent cancel"],
    },
    CommandSpec {
        group: "Agent",
        name: "agent mcp-token",
        summary: "Create a lease-scoped MCP token file.",
        usage: "bowline agent mcp-token --lease <id> [--json]",
        options: &[LEASE_ID_OPTION, GLOBAL_JSON_OPTION],
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "AgentMcpTokenCommandOutput",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: false,
        bounded_output: None,
        related_commands: &["mcp", "agent context"],
    },
];
