use super::*;

pub(super) const COMMAND_REGISTRY: &[CommandSpec] = &[
    CommandSpec {
        group: "Discovery",
        name: "help",
        summary: "Show human or JSON help for every CLI command.",
        usage: "bowline help [topic] [--json]",
        options: &[GLOBAL_JSON_OPTION],
        positionals: HELP_POSITIONALS,
        examples: &[ExampleSpec {
            command: "bowline help work create --json",
            summary: "Inspect nested help for work-view creation.",
        }],
        json_output_type: "HelpCommandOutput",
        side_effect_level: SideEffectLevel::None,
        bounded_output: None,
        related_commands: &["contract", "version"],
    },
    CommandSpec {
        group: "Discovery",
        name: "version",
        summary: "Print CLI version and protocol compatibility.",
        usage: "bowline version [--json]",
        options: &[GLOBAL_JSON_OPTION],
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "VersionCommandOutput",
        side_effect_level: SideEffectLevel::None,
        bounded_output: None,
        related_commands: &["contract"],
    },
    CommandSpec {
        group: "Discovery",
        name: "contract",
        summary: "Print the machine-readable CLI command and output contract.",
        usage: "bowline contract [topic] [--summary] [--json]",
        options: &[CONTRACT_SUMMARY_OPTION, GLOBAL_JSON_OPTION],
        positionals: HELP_POSITIONALS,
        examples: &[
            ExampleSpec {
                command: "bowline contract --summary --json",
                summary: "Print the compact command discovery index.",
            },
            ExampleSpec {
                command: "bowline contract work diff --json",
                summary: "Fetch one full command descriptor.",
            },
        ],
        json_output_type: "ContractCommandOutput",
        side_effect_level: SideEffectLevel::None,
        bounded_output: None,
        related_commands: &["help", "version"],
    },
    CommandSpec {
        group: "Workspace",
        name: "update",
        summary: "Check for or install the latest Bowline release.",
        usage: "bowline update [--check] [--version <version>] [--json]",
        options: &[
            OptionSpec {
                name: "--check",
                value_name: None,
                summary: "Only check whether an update is available.",
                required: false,
                repeatable: false,
            },
            OptionSpec {
                name: "--version",
                value_name: Some("version"),
                summary: "Install or check a specific release version.",
                required: false,
                repeatable: false,
            },
            GLOBAL_JSON_OPTION,
        ],
        positionals: NO_POSITIONALS,
        examples: &[ExampleSpec {
            command: "bowline update --check --json",
            summary: "Check the install host release manifest.",
        }],
        json_output_type: "UpdateCommandOutput",
        side_effect_level: SideEffectLevel::Mutation,
        bounded_output: None,
        related_commands: &["version", "status"],
    },
    CommandSpec {
        group: "Workspace",
        name: "login",
        summary: "Sign in and onboard this machine with the default ~/Code workspace.",
        usage: "bowline login [--headless] [--no-poll] [--json]",
        options: &[
            OptionSpec {
                name: "--headless",
                value_name: None,
                summary: "Start login without interactive polling.",
                required: false,
                repeatable: false,
            },
            OptionSpec {
                name: "--no-poll",
                value_name: None,
                summary: "Print the pending login instructions and exit without polling.",
                required: false,
                repeatable: false,
            },
            GLOBAL_JSON_OPTION,
        ],
        positionals: NO_POSITIONALS,
        examples: &[ExampleSpec {
            command: "bowline setup --root ~/Projects",
            summary: "Use an explicit workspace root instead of ~/Code.",
        }],
        json_output_type: "LoginCommandOutput | SetupCommandOutput",
        side_effect_level: SideEffectLevel::Mutation,
        bounded_output: None,
        related_commands: &["setup", "logout"],
    },
    CommandSpec {
        group: "Workspace",
        name: "logout",
        summary: "Clear the saved local account session without removing device trust.",
        usage: "bowline logout [--json]",
        options: &[GLOBAL_JSON_OPTION],
        positionals: NO_POSITIONALS,
        examples: &[ExampleSpec {
            command: "bowline logout",
            summary: "Sign this machine out of the current account session.",
        }],
        json_output_type: "LogoutCommandOutput",
        side_effect_level: SideEffectLevel::Mutation,
        bounded_output: None,
        related_commands: &["login", "status"],
    },
    CommandSpec {
        group: "Workspace",
        name: "status",
        summary: "Inspect workspace, sync, and safe next actions.",
        usage: "bowline status [--root <path>] [--project <path>] [--watch] [--all] [--json]",
        options: &[
            OPTIONAL_ROOT_OPTION,
            PROJECT_OPTION,
            OptionSpec {
                name: "--watch",
                value_name: None,
                summary: "Stream status frames.",
                required: false,
                repeatable: false,
            },
            OptionSpec {
                name: "--all",
                value_name: None,
                summary: "Include retained and archived work status.",
                required: false,
                repeatable: false,
            },
            GLOBAL_JSON_OPTION,
        ],
        positionals: NO_POSITIONALS,
        examples: &[ExampleSpec {
            command: "bowline status --root ~/Code --json",
            summary: "Parse the current workspace status.",
        }],
        json_output_type: "StatusCommandOutput",
        side_effect_level: SideEffectLevel::Read,
        bounded_output: None,
        related_commands: &["events", "diagnostics collect"],
    },
    CommandSpec {
        group: "Workspace",
        name: "setup",
        summary: "Set up this machine or prepare one project for Bowline.",
        usage: "bowline setup [--root <path>] [--socket <path>] [--json] | bowline setup <path> [--yes] [--socket <path>] [--json]",
        options: &[
            OPTIONAL_ROOT_OPTION,
            OptionSpec {
                name: "--yes",
                value_name: None,
                summary: "Approve required project setup changes when a path is provided.",
                required: false,
                repeatable: false,
            },
            SOCKET_OPTION,
            GLOBAL_JSON_OPTION,
        ],
        positionals: OPTIONAL_PROJECT_POSITIONAL,
        examples: &[
            ExampleSpec {
                command: "bowline setup",
                summary: "Onboard this machine with the default workspace root.",
            },
            ExampleSpec {
                command: "bowline setup . --json",
                summary: "Prepare the current project and emit setup receipts.",
            },
        ],
        json_output_type: "SetupCommandOutput | SetupProjectOutput",
        side_effect_level: SideEffectLevel::Mutation,
        bounded_output: None,
        related_commands: &["login", "status"],
    },
    CommandSpec {
        group: "Workspace",
        name: "conflicts",
        summary: "List files whose incoming version is waiting beside them.",
        usage: "bowline conflicts [--root <path>] [--project <path>] [--json|--human|--quiet]",
        options: &[
            OPTIONAL_ROOT_OPTION,
            PROJECT_OPTION,
            GLOBAL_JSON_OPTION,
            QUIET_OPTION,
        ],
        positionals: NO_POSITIONALS,
        examples: &[ExampleSpec {
            command: "bowline conflicts --json",
            summary: "List every unreconciled conflict with the command that resolves it.",
        }],
        json_output_type: "ConflictsCommandOutput",
        side_effect_level: SideEffectLevel::Read,
        bounded_output: None,
        related_commands: &["resolve", "status"],
    },
    CommandSpec {
        group: "Workspace",
        name: "resolve",
        summary: "Reconcile one conflict: keep your file, take the incoming one, or diff them.",
        usage: "bowline resolve <aside-path> (--keep-local | --take-remote | --diff) [--root <path>] [--json] [--dry-run]",
        options: &[
            OptionSpec {
                name: "--keep-local",
                value_name: None,
                summary: "Keep the file as it stands and discard the incoming version.",
                required: false,
                repeatable: false,
            },
            OptionSpec {
                name: "--take-remote",
                value_name: None,
                summary: "Replace the file with the incoming version.",
                required: false,
                repeatable: false,
            },
            OptionSpec {
                name: "--diff",
                value_name: None,
                summary: "Print the difference between the two versions and change nothing.",
                required: false,
                repeatable: false,
            },
            OPTIONAL_ROOT_OPTION,
            GLOBAL_JSON_OPTION,
            DRY_RUN_OPTION,
        ],
        positionals: REQUIRED_CONFLICT_ASIDE_POSITIONAL,
        examples: &[
            ExampleSpec {
                command: "bowline resolve 'src/auth.ts.bowline-conflict.9f3a2c1d' --diff",
                summary: "Read the difference before choosing a side.",
            },
            ExampleSpec {
                command: "bowline resolve 'src/auth.ts.bowline-conflict.9f3a2c1d' --take-remote",
                summary: "Adopt the incoming version and clear the conflict.",
            },
        ],
        json_output_type: "ResolveCommandOutput",
        // `--diff` prints and returns `changed: false`; only `--keep-local` and
        // `--take-remote` touch the workspace. A harness that gates on the
        // declared level would otherwise prompt for a read.
        side_effect_level: SideEffectLevel::ConditionalMutation,
        bounded_output: None,
        related_commands: &["conflicts", "status"],
    },
    CommandSpec {
        group: "Workspace",
        name: "deletions",
        summary: "Show the deletion sync refuses to publish, and confirm it.",
        usage: "bowline deletions [--confirm] [--socket <path>] [--json] [--dry-run]",
        options: &[
            OptionSpec {
                name: "--confirm",
                value_name: None,
                summary: "Authorise the refused deletion. Applies to one push only.",
                required: false,
                repeatable: false,
            },
            SOCKET_OPTION,
            GLOBAL_JSON_OPTION,
            DRY_RUN_OPTION,
        ],
        positionals: NO_POSITIONALS,
        examples: &[
            ExampleSpec {
                command: "bowline deletions",
                summary: "List the files a refused push would delete everywhere.",
            },
            ExampleSpec {
                command: "bowline deletions --confirm",
                summary: "Agree the deletions are real and let sync publish them.",
            },
        ],
        json_output_type: "DeletionsCommandOutput",
        // Without `--confirm` this only reads the daemon's engine state; with it
        // the next push publishes deletions to every device. A harness that gated
        // on the declared level would otherwise prompt for a read.
        side_effect_level: SideEffectLevel::ConditionalMutation,
        bounded_output: None,
        related_commands: &["status", "conflicts"],
    },
    CommandSpec {
        group: "Workspace",
        name: "events",
        summary: "List recent workspace events.",
        usage: "bowline events [--root <path>] [--project <path>] [--limit <n>] [--json|--human|--quiet]",
        options: &[
            OPTIONAL_ROOT_OPTION,
            PROJECT_OPTION,
            LIMIT_OPTION,
            GLOBAL_JSON_OPTION,
            QUIET_OPTION,
        ],
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "EventsCommandOutput",
        side_effect_level: SideEffectLevel::Read,
        bounded_output: None,
        related_commands: &["status"],
    },
    CommandSpec {
        group: "Workspace",
        name: "tui",
        summary: "Open the terminal workspace UI.",
        usage: "bowline tui [--root <path>] [--project <path>] [--socket <path>]",
        options: &[OPTIONAL_ROOT_OPTION, PROJECT_OPTION, SOCKET_OPTION],
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "none",
        side_effect_level: SideEffectLevel::Interactive,
        bounded_output: None,
        related_commands: &["status"],
    },
    CommandSpec {
        group: "Workspace",
        name: "forget-local",
        summary: "Remove one materialized project from this device after preview.",
        usage: "bowline forget-local <project> [--yes] [--json] [--dry-run]",
        options: &[
            OptionSpec {
                name: "--yes",
                value_name: None,
                summary: "Remove local bytes after reviewing the preview.",
                required: false,
                repeatable: false,
            },
            GLOBAL_JSON_OPTION,
            DRY_RUN_OPTION,
        ],
        positionals: REQUIRED_PROJECT_POSITIONAL,
        examples: &[ExampleSpec {
            command: "bowline forget-local apps/web --dry-run",
            summary: "Preview local bytes that would be removed on this device.",
        }],
        json_output_type: "NamespaceLifecycleCommandOutput",
        side_effect_level: SideEffectLevel::LocalFilesystemDelete,
        bounded_output: None,
        related_commands: &["setup", "archive", "purge"],
    },
    CommandSpec {
        group: "Workspace",
        name: "archive",
        summary: "Hide one project from default namespace views without deleting local bytes.",
        usage: "bowline archive <project> [--restore] [--json] [--dry-run]",
        options: &[
            OptionSpec {
                name: "--restore",
                value_name: None,
                summary: "Restore an archived project to active namespace views.",
                required: false,
                repeatable: false,
            },
            GLOBAL_JSON_OPTION,
            DRY_RUN_OPTION,
        ],
        positionals: REQUIRED_PROJECT_POSITIONAL,
        examples: &[ExampleSpec {
            command: "bowline archive apps/web --dry-run",
            summary: "Preview the archive transition.",
        }],
        json_output_type: "NamespaceLifecycleCommandOutput",
        side_effect_level: SideEffectLevel::WorkspaceMetadata,
        bounded_output: None,
        related_commands: &["forget-local", "purge", "status"],
    },
    CommandSpec {
        group: "Workspace",
        name: "purge",
        summary: "Schedule remote destruction for an archived project after a grace window.",
        usage: "bowline purge <project> [--grace <days>|--cancel] [--json] [--dry-run]",
        options: &[
            OptionSpec {
                name: "--grace",
                value_name: Some("days"),
                summary: "Grace period before remote objects become collectible; allowed range is 1-90 days.",
                required: false,
                repeatable: false,
            },
            OptionSpec {
                name: "--cancel",
                value_name: None,
                summary: "Cancel a purge-pending project and keep it archived.",
                required: false,
                repeatable: false,
            },
            GLOBAL_JSON_OPTION,
            DRY_RUN_OPTION,
        ],
        positionals: REQUIRED_PROJECT_POSITIONAL,
        examples: &[ExampleSpec {
            command: "bowline purge apps/web --dry-run",
            summary: "Preview the remote-retention impact before scheduling purge.",
        }],
        json_output_type: "NamespaceLifecycleCommandOutput",
        side_effect_level: SideEffectLevel::RemoteDestructionScheduled,
        bounded_output: None,
        related_commands: &["archive", "forget-local", "status"],
    },
    CommandSpec {
        group: "Trust",
        name: "device approve",
        summary: "Approve a pending device trust request.",
        usage: "bowline device approve [--root <path>] (--request <id>|--code <short-code>) [--yes] [--json] [--dry-run]",
        options: &[
            OPTIONAL_ROOT_OPTION,
            REQUEST_OPTION,
            CODE_OPTION,
            OptionSpec {
                name: "--yes",
                value_name: None,
                summary: "Approve without an interactive prompt.",
                required: false,
                repeatable: false,
            },
            GLOBAL_JSON_OPTION,
            DRY_RUN_OPTION,
        ],
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "DevicesCommandOutput",
        side_effect_level: SideEffectLevel::TrustChange,
        bounded_output: None,
        related_commands: &["device deny", "device revoke", "device list"],
    },
    CommandSpec {
        group: "Trust",
        name: "device deny",
        summary: "Deny a pending device trust request.",
        usage: "bowline device deny [--root <path>] (--request <id>|--code <short-code>) [--json] [--dry-run]",
        options: &[
            OPTIONAL_ROOT_OPTION,
            REQUEST_OPTION,
            CODE_OPTION,
            GLOBAL_JSON_OPTION,
            DRY_RUN_OPTION,
        ],
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "DevicesCommandOutput",
        side_effect_level: SideEffectLevel::TrustChange,
        bounded_output: None,
        related_commands: &["device approve", "device revoke", "device list"],
    },
    CommandSpec {
        group: "Trust",
        name: "device revoke",
        summary: "Revoke a trusted device.",
        usage: "bowline device revoke [--root <path>] --device <id> [--json] [--dry-run]",
        options: &[
            OPTIONAL_ROOT_OPTION,
            DEVICE_OPTION,
            GLOBAL_JSON_OPTION,
            DRY_RUN_OPTION,
        ],
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "DevicesCommandOutput",
        side_effect_level: SideEffectLevel::TrustChange,
        bounded_output: None,
        related_commands: &["device approve", "device deny", "device list"],
    },
    CommandSpec {
        group: "Trust",
        name: "device list",
        summary: "List local device records.",
        usage: "bowline device list [--root <path>] [--json|--human|--quiet]",
        options: &[OPTIONAL_ROOT_OPTION, GLOBAL_JSON_OPTION, QUIET_OPTION],
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "DevicesCommandOutput",
        side_effect_level: SideEffectLevel::Read,
        bounded_output: None,
        related_commands: &["device approve", "device revoke", "device request"],
    },
    CommandSpec {
        group: "Trust",
        name: "device request",
        summary: "Raise a device approval request for this machine.",
        usage: "bowline device request [--root <path>] [--json]",
        options: &[OPTIONAL_ROOT_OPTION, GLOBAL_JSON_OPTION],
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "DevicesCommandOutput",
        side_effect_level: SideEffectLevel::Mutation,
        bounded_output: None,
        related_commands: &["device accept", "device approve", "device list"],
    },
    CommandSpec {
        group: "Trust",
        name: "device accept",
        summary: "Accept an encrypted device grant for this machine.",
        usage: "bowline device accept [--root <path>] --request <id> [--json]",
        options: &[OPTIONAL_ROOT_OPTION, REQUEST_OPTION, GLOBAL_JSON_OPTION],
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "DevicesCommandOutput",
        side_effect_level: SideEffectLevel::Mutation,
        bounded_output: None,
        related_commands: &["device request", "device approve", "device list"],
    },
    CommandSpec {
        group: "Trust",
        name: "device key-status",
        summary: "Report whether this device holds workspace key material.",
        usage: "bowline device key-status --workspace <id> [--json]",
        options: &[WORKSPACE_ID_OPTION, GLOBAL_JSON_OPTION],
        positionals: NO_POSITIONALS,
        examples: &[ExampleSpec {
            command: "bowline device key-status --workspace ws_123 --json",
            summary: "Ask the local secret store whether this host can open the workspace.",
        }],
        json_output_type: "DeviceKeyStatusCommandOutput",
        side_effect_level: SideEffectLevel::Read,
        bounded_output: None,
        related_commands: &["device accept", "device request", "device list"],
    },
    CommandSpec {
        group: "Trust",
        name: "recover status",
        summary: "Report Recovery Key state for this workspace.",
        usage: "bowline recover status [--json]",
        options: &[GLOBAL_JSON_OPTION],
        positionals: NO_POSITIONALS,
        examples: &[ExampleSpec {
            command: "bowline recover status --json",
            summary: "Read which Recovery Keys exist and which one is active.",
        }],
        json_output_type: "RecoveryCommandOutput",
        side_effect_level: SideEffectLevel::Read,
        bounded_output: None,
        related_commands: &["recover create", "recover use"],
    },
    CommandSpec {
        group: "Trust",
        name: "recover create",
        summary: "Create a Recovery Key and print its words once.",
        usage: "bowline recover create [--json] [--dry-run]",
        options: &[GLOBAL_JSON_OPTION, DRY_RUN_OPTION],
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "RecoveryCommandOutput",
        side_effect_level: SideEffectLevel::SecretMaterial,
        bounded_output: None,
        related_commands: &["recover status", "recover rotate"],
    },
    CommandSpec {
        group: "Trust",
        name: "recover verify",
        summary: "Check Recovery Key words from stdin without granting access.",
        usage: "bowline recover verify <envelope-id> [--json]",
        options: &[GLOBAL_JSON_OPTION],
        positionals: REQUIRED_ENVELOPE_POSITIONAL,
        examples: &[ExampleSpec {
            command: "printf '%s' \"$RECOVERY_WORDS\" | bowline recover verify env_123 --json",
            summary: "Confirm stored words still match the Recovery Key.",
        }],
        json_output_type: "RecoveryCommandOutput",
        side_effect_level: SideEffectLevel::Read,
        bounded_output: None,
        related_commands: &["recover status", "recover use"],
    },
    CommandSpec {
        group: "Trust",
        name: "recover rotate",
        summary: "Mint a fresh Recovery Key and invalidate the previous one.",
        usage: "bowline recover rotate [--json] [--dry-run]",
        options: &[GLOBAL_JSON_OPTION, DRY_RUN_OPTION],
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "RecoveryCommandOutput",
        side_effect_level: SideEffectLevel::SecretMaterial,
        bounded_output: None,
        related_commands: &["recover create", "recover revoke"],
    },
    CommandSpec {
        group: "Trust",
        name: "recover revoke",
        summary: "Permanently revoke a Recovery Key.",
        usage: "bowline recover revoke <envelope-id> [--json] [--dry-run]",
        options: &[GLOBAL_JSON_OPTION, DRY_RUN_OPTION],
        positionals: REQUIRED_ENVELOPE_POSITIONAL,
        examples: EMPTY_EXAMPLES,
        json_output_type: "RecoveryCommandOutput",
        side_effect_level: SideEffectLevel::TrustChange,
        bounded_output: None,
        related_commands: &["recover rotate", "recover status"],
    },
    CommandSpec {
        group: "Trust",
        name: "recover use",
        summary: "Grant this device workspace access with Recovery Key words from stdin.",
        usage: "bowline recover use <envelope-id> [--json] [--dry-run]",
        options: &[GLOBAL_JSON_OPTION, DRY_RUN_OPTION],
        positionals: REQUIRED_ENVELOPE_POSITIONAL,
        examples: &[ExampleSpec {
            command: "printf '%s' \"$RECOVERY_WORDS\" | bowline recover use env_123",
            summary: "Recover access on a device with no trusted peer available.",
        }],
        json_output_type: "RecoveryCommandOutput",
        side_effect_level: SideEffectLevel::SecretMaterial,
        bounded_output: None,
        related_commands: &["recover status", "device approve"],
    },
    CommandSpec {
        group: "Remote",
        name: "connect",
        summary: "Inbound SSH: install and trust a machine you own.",
        usage: "bowline connect <host> [--root <path>] [--binary <path>] [--json] [--dry-run]",
        options: CONNECT_OPTIONS,
        positionals: REQUIRED_TARGET_POSITIONAL,
        examples: EMPTY_EXAMPLES,
        json_output_type: "BootstrapSshCommandOutput",
        side_effect_level: SideEffectLevel::RemoteMutation,
        bounded_output: None,
        related_commands: &["device request", "device approve"],
    },
];
