use super::*;

pub(super) const COMMAND_REGISTRY: &[CommandSpec] = &[
    CommandSpec {
        group: "Work",
        name: "work create",
        summary: "Create or reuse a named work view for a project.",
        usage: "bowline work create [project] <name> [--from <restore-point>] [--json] [--dry-run]",
        options: WORK_CREATE_OPTIONS,
        positionals: WORK_CREATE_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "WorkCreateCommandOutput",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: true,
        bounded_output: None,
        related_commands: &["work review", "work accept", "work discard"],
    },
    CommandSpec {
        group: "Work",
        name: "work list",
        summary: "List work views.",
        usage: "bowline work list [--all] [--json|--human|--quiet]",
        options: WORK_LIST_OPTIONS,
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "WorkListCommandOutput",
        side_effect_level: "read",
        supports_json: true,
        supports_dry_run: false,
        bounded_output: None,
        related_commands: &["work create"],
    },
    CommandSpec {
        group: "Work",
        name: "work diff",
        summary: "Show the diff for a work view.",
        usage: "bowline work diff [target] [--path <glob>...] [--json]",
        options: &[WORK_PATH_OPTION, GLOBAL_JSON_OPTION],
        positionals: OPTIONAL_TARGET_POSITIONAL,
        examples: EMPTY_EXAMPLES,
        json_output_type: "WorkDiffCommandOutput",
        side_effect_level: "read",
        supports_json: true,
        supports_dry_run: false,
        bounded_output: None,
        related_commands: &["work review"],
    },
    CommandSpec {
        group: "Work",
        name: "work review",
        summary: "Preview whether a work view is ready to accept.",
        usage: "bowline work review <target> [--path <glob>...] [--json]",
        options: &[WORK_PATH_OPTION, GLOBAL_JSON_OPTION],
        positionals: REQUIRED_TARGET_POSITIONAL,
        examples: EMPTY_EXAMPLES,
        json_output_type: "WorkDiffCommandOutput",
        side_effect_level: "read",
        supports_json: true,
        supports_dry_run: false,
        bounded_output: None,
        related_commands: &["work accept"],
    },
    CommandSpec {
        group: "Work",
        name: "work accept",
        summary: "Apply a review-ready work view.",
        usage: "bowline work accept <target> [--path <glob>...] [--json] [--dry-run]",
        options: &[WORK_PATH_OPTION, GLOBAL_JSON_OPTION, DRY_RUN_OPTION],
        positionals: REQUIRED_TARGET_POSITIONAL,
        examples: EMPTY_EXAMPLES,
        json_output_type: "WorkLifecycleCommandOutput",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: true,
        bounded_output: None,
        related_commands: &["work review"],
    },
    CommandSpec {
        group: "Work",
        name: "work discard",
        summary: "Discard a work view.",
        usage: "bowline work discard <target> [--json] [--dry-run]",
        options: &[GLOBAL_JSON_OPTION, DRY_RUN_OPTION],
        positionals: REQUIRED_TARGET_POSITIONAL,
        examples: EMPTY_EXAMPLES,
        json_output_type: "WorkLifecycleCommandOutput",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: true,
        bounded_output: None,
        related_commands: &["work list"],
    },
    CommandSpec {
        group: "Work",
        name: "work restore",
        summary: "Restore a discarded work view.",
        usage: "bowline work restore <target> [--json] [--dry-run]",
        options: &[GLOBAL_JSON_OPTION, DRY_RUN_OPTION],
        positionals: REQUIRED_TARGET_POSITIONAL,
        examples: EMPTY_EXAMPLES,
        json_output_type: "WorkLifecycleCommandOutput",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: true,
        bounded_output: None,
        related_commands: &["work list"],
    },
    CommandSpec {
        group: "Work",
        name: "work cleanup",
        summary: "Preview or apply cleanup for retained work views.",
        usage: "bowline work cleanup [--apply] [--json] [--dry-run]",
        options: &[
            OptionSpec {
                name: "--apply",
                value_name: None,
                summary: "Apply cleanup instead of previewing it.",
                required: false,
                repeatable: false,
            },
            GLOBAL_JSON_OPTION,
            DRY_RUN_OPTION,
        ],
        positionals: NO_POSITIONALS,
        examples: EMPTY_EXAMPLES,
        json_output_type: "WorkCleanupCommandOutput",
        side_effect_level: "conditional-mutation",
        supports_json: true,
        supports_dry_run: true,
        bounded_output: None,
        related_commands: &["work list"],
    },
];
