// Generated by Bowline wire-contract generator 1.2.0. Do not edit.
// Schema SHA-256: 90aaff183a675d00a355085f8a588d3d135b786f9e88fb8cde5c8a153078173e

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

use super::generated::Timestamp;

pub const KNOWN_STATUS_AVAILABILITIES: &[&str] = &["ready", "degraded", "unavailable"];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum StatusAvailability {
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "degraded")]
    Degraded,
    #[serde(rename = "unavailable")]
    Unavailable,
}

impl StatusAvailability {
    pub const ALL: &'static [Self] = &[Self::Ready, Self::Degraded, Self::Unavailable];

    pub const fn token(self) -> &'static str {
        match self {
            Self::Ready => "ready",
            Self::Degraded => "degraded",
            Self::Unavailable => "unavailable",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "ready" => Some(Self::Ready),
            "degraded" => Some(Self::Degraded),
            "unavailable" => Some(Self::Unavailable),
            _ => None,
        }
    }
}

pub const KNOWN_STATUS_ATTENTIONS: &[&str] = &["none", "recommended", "required"];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum StatusAttention {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "recommended")]
    Recommended,
    #[serde(rename = "required")]
    Required,
}

impl StatusAttention {
    pub const ALL: &'static [Self] = &[Self::None, Self::Recommended, Self::Required];

    pub const fn token(self) -> &'static str {
        match self {
            Self::None => "none",
            Self::Recommended => "recommended",
            Self::Required => "required",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "none" => Some(Self::None),
            "recommended" => Some(Self::Recommended),
            "required" => Some(Self::Required),
            _ => None,
        }
    }
}

pub const KNOWN_STATUS_FACT_SCOPES: &[&str] = &[
    "account",
    "workspace",
    "project",
    "device",
    "session",
    "work_view",
    "lease",
    "path",
];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum StatusFactScope {
    #[serde(rename = "account")]
    Account,
    #[serde(rename = "workspace")]
    Workspace,
    #[serde(rename = "project")]
    Project,
    #[serde(rename = "device")]
    Device,
    #[serde(rename = "session")]
    Session,
    #[serde(rename = "work_view")]
    WorkView,
    #[serde(rename = "lease")]
    Lease,
    #[serde(rename = "path")]
    Path,
}

impl StatusFactScope {
    pub const ALL: &'static [Self] = &[
        Self::Account,
        Self::Workspace,
        Self::Project,
        Self::Device,
        Self::Session,
        Self::WorkView,
        Self::Lease,
        Self::Path,
    ];

    pub const fn token(self) -> &'static str {
        match self {
            Self::Account => "account",
            Self::Workspace => "workspace",
            Self::Project => "project",
            Self::Device => "device",
            Self::Session => "session",
            Self::WorkView => "work_view",
            Self::Lease => "lease",
            Self::Path => "path",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "account" => Some(Self::Account),
            "workspace" => Some(Self::Workspace),
            "project" => Some(Self::Project),
            "device" => Some(Self::Device),
            "session" => Some(Self::Session),
            "work_view" => Some(Self::WorkView),
            "lease" => Some(Self::Lease),
            "path" => Some(Self::Path),
            _ => None,
        }
    }
}

pub const KNOWN_STATUS_FRESHNESSS: &[&str] = &["fresh", "stale", "unknown"];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum StatusFreshness {
    #[serde(rename = "fresh")]
    Fresh,
    #[serde(rename = "stale")]
    Stale,
    #[serde(rename = "unknown")]
    Unknown,
}

impl StatusFreshness {
    pub const ALL: &'static [Self] = &[Self::Fresh, Self::Stale, Self::Unknown];

    pub const fn token(self) -> &'static str {
        match self {
            Self::Fresh => "fresh",
            Self::Stale => "stale",
            Self::Unknown => "unknown",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "fresh" => Some(Self::Fresh),
            "stale" => Some(Self::Stale),
            "unknown" => Some(Self::Unknown),
            _ => None,
        }
    }
}

pub const KNOWN_STATUS_FACT_AVAILABILITY_IMPACTS: &[&str] = &["none", "degraded", "unavailable"];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum StatusFactAvailabilityImpact {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "degraded")]
    Degraded,
    #[serde(rename = "unavailable")]
    Unavailable,
}

impl StatusFactAvailabilityImpact {
    pub const ALL: &'static [Self] = &[Self::None, Self::Degraded, Self::Unavailable];

    pub const fn token(self) -> &'static str {
        match self {
            Self::None => "none",
            Self::Degraded => "degraded",
            Self::Unavailable => "unavailable",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "none" => Some(Self::None),
            "degraded" => Some(Self::Degraded),
            "unavailable" => Some(Self::Unavailable),
            _ => None,
        }
    }
}

pub const KNOWN_STATUS_FACT_ATTENTION_IMPACTS: &[&str] = &["none", "recommended", "required"];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum StatusFactAttentionImpact {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "recommended")]
    Recommended,
    #[serde(rename = "required")]
    Required,
}

impl StatusFactAttentionImpact {
    pub const ALL: &'static [Self] = &[Self::None, Self::Recommended, Self::Required];

    pub const fn token(self) -> &'static str {
        match self {
            Self::None => "none",
            Self::Recommended => "recommended",
            Self::Required => "required",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "none" => Some(Self::None),
            "recommended" => Some(Self::Recommended),
            "required" => Some(Self::Required),
            _ => None,
        }
    }
}

pub type StatusFactId = String;

pub type StatusFactKind = String;

pub type StatusActionKind = String;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StatusActionReference {
    pub kind: StatusActionKind,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub target_id: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StatusFact {
    pub id: StatusFactId,
    pub kind: StatusFactKind,
    pub source: String,
    pub scope: StatusFactScope,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scope_id: Option<String>,
    pub availability_impact: StatusFactAvailabilityImpact,
    pub attention_impact: StatusFactAttentionImpact,
    pub summary_key: String,
    pub parameters: BTreeMap<String, String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub action: Option<StatusActionReference>,
    pub observed_at: Timestamp,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stale_after: Option<Timestamp>,
    pub dedupe_key: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StatusSummary {
    pub availability: StatusAvailability,
    pub attention: StatusAttention,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub primary_fact_id: Option<StatusFactId>,
    pub facts: Vec<StatusFact>,
    pub snapshot_version: u64,
    pub observed_at: Timestamp,
    pub freshness: StatusFreshness,
}
