// Generated by Bowline wire-contract generator 1.2.0. Do not edit.
// Schema SHA-256: 4ba7588109ebc1681e45961ce7cfc67a1cfb121e39447807957b0f64adb3ab98

use std::fmt;

use serde::{Deserialize, Deserializer, Serialize, Serializer};

use super::generated::{OpaqueJson, WireStatusCommandOutput};

pub const KNOWN_DAEMON_RPC_ERROR_CODES: &[&str] = &[
    "invalid_request",
    "unsupported_version",
    "method_not_found",
    "malformed_frame",
    "frame_too_large",
    "deadline_exceeded",
    "cancelled",
    "overloaded",
    "resource_exhausted",
    "conflict",
    "not_found",
    "unavailable",
    "permission_denied",
    "internal",
];

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum DaemonRpcErrorCode {
    InvalidRequest,
    UnsupportedVersion,
    MethodNotFound,
    MalformedFrame,
    FrameTooLarge,
    DeadlineExceeded,
    Cancelled,
    Overloaded,
    ResourceExhausted,
    Conflict,
    NotFound,
    Unavailable,
    PermissionDenied,
    Internal,
    Unknown(String),
}

impl DaemonRpcErrorCode {
    pub fn as_str(&self) -> &str {
        match self {
            Self::InvalidRequest => "invalid_request",
            Self::UnsupportedVersion => "unsupported_version",
            Self::MethodNotFound => "method_not_found",
            Self::MalformedFrame => "malformed_frame",
            Self::FrameTooLarge => "frame_too_large",
            Self::DeadlineExceeded => "deadline_exceeded",
            Self::Cancelled => "cancelled",
            Self::Overloaded => "overloaded",
            Self::ResourceExhausted => "resource_exhausted",
            Self::Conflict => "conflict",
            Self::NotFound => "not_found",
            Self::Unavailable => "unavailable",
            Self::PermissionDenied => "permission_denied",
            Self::Internal => "internal",
            Self::Unknown(raw) => raw,
        }
    }
}

impl fmt::Display for DaemonRpcErrorCode {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

impl Serialize for DaemonRpcErrorCode {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for DaemonRpcErrorCode {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let raw = String::deserialize(deserializer)?;
        Ok(match raw.as_str() {
            "invalid_request" => Self::InvalidRequest,
            "unsupported_version" => Self::UnsupportedVersion,
            "method_not_found" => Self::MethodNotFound,
            "malformed_frame" => Self::MalformedFrame,
            "frame_too_large" => Self::FrameTooLarge,
            "deadline_exceeded" => Self::DeadlineExceeded,
            "cancelled" => Self::Cancelled,
            "overloaded" => Self::Overloaded,
            "resource_exhausted" => Self::ResourceExhausted,
            "conflict" => Self::Conflict,
            "not_found" => Self::NotFound,
            "unavailable" => Self::Unavailable,
            "permission_denied" => Self::PermissionDenied,
            "internal" => Self::Internal,
            _ => Self::Unknown(raw),
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DaemonClientHello {
    pub protocol: String,
    pub protocol_version: u16,
    pub contract_version: u16,
    pub schema_hash: String,
    pub client_kind: String,
    pub client_version: String,
    pub capabilities: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DaemonServerHello {
    pub protocol_version: u16,
    pub contract_version: u16,
    pub schema_hash: String,
    pub daemon_version: String,
    pub capabilities: Vec<String>,
    pub instance_id: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DaemonRpcError {
    pub code: DaemonRpcErrorCode,
    pub message: String,
    pub retryable: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub retry_after_ms: Option<u32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub operation_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub required_client_version: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub details: Option<OpaqueJson>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonRpcRequest {
    pub request_id: String,
    pub method: String,
    pub params: OpaqueJson,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deadline_ms: Option<u32>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonRpcResponse {
    pub request_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub result: Option<OpaqueJson>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<DaemonRpcError>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonRpcEvent {
    pub subscription_id: String,
    pub sequence: u64,
    pub event_kind: String,
    pub payload: OpaqueJson,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonRpcCancel {
    pub request_id: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonStatusScopeParams {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub workspace_root: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub project_path: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requested_path: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonStatusSnapshotResult {
    pub instance_id: String,
    pub sequence: u64,
    pub snapshot: WireStatusCommandOutput,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonStatusSubscribeResult {
    pub subscription_id: String,
    pub instance_id: String,
    pub sequence: u64,
    pub snapshot: WireStatusCommandOutput,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonStatusEventPayload {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub snapshot: Option<WireStatusCommandOutput>,
    pub gap: bool,
    pub resync_required: bool,
    pub heartbeat: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonDeviceActionParams {
    pub request_id: String,
    pub idempotency_key: String,
}

pub const KNOWN_DAEMON_SYNC_RESOURCE_KINDS: &[&str] =
    &["workspace-sync", "conflict-followup", "post-commit"];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum DaemonSyncResourceKind {
    #[serde(rename = "workspace-sync")]
    WorkspaceSync,
    #[serde(rename = "conflict-followup")]
    ConflictFollowup,
    #[serde(rename = "post-commit")]
    PostCommit,
}

impl DaemonSyncResourceKind {
    pub const ALL: &'static [Self] = &[
        Self::WorkspaceSync,
        Self::ConflictFollowup,
        Self::PostCommit,
    ];

    pub const fn token(self) -> &'static str {
        match self {
            Self::WorkspaceSync => "workspace-sync",
            Self::ConflictFollowup => "conflict-followup",
            Self::PostCommit => "post-commit",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "workspace-sync" => Some(Self::WorkspaceSync),
            "conflict-followup" => Some(Self::ConflictFollowup),
            "post-commit" => Some(Self::PostCommit),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonSyncResource {
    pub kind: DaemonSyncResourceKind,
    pub workspace_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conflict_id: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonCancelOperationParams {
    pub operation_id: String,
}
