// Generated by Bowline wire-contract generator 1.2.0. Do not edit.
// Schema SHA-256: 90aaff183a675d00a355085f8a588d3d135b786f9e88fb8cde5c8a153078173e

use super::generated::{
    WireControlPlaneSupportCapability, WireFreshnessAxis, WireFreshnessVerdict,
    WireProjectSetupReadinessState, WireSetupReceiptState, WireStatusLevel,
};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WireProjectAttentionSummary {
    pub project_id: String,
    pub path: String,
    pub level: WireStatusLevel,
    pub summary: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WireObservedWorkspaceSummary {
    pub repo_count: u64,
    pub no_remote_repo_count: u64,
    pub stale_remote_tracking_repo_count: u64,
    pub git_partial_project_count: u64,
    pub git_unavailable_project_count: u64,
    pub generated_path_count: u64,
    pub dependency_path_count: u64,
    pub env_file_count: u64,
    pub untracked_file_count: u64,
    pub local_only_path_count: u64,
    pub blocked_path_count: u64,
    pub workspace_sync_path_count: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WireWorkspaceSummary {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub projects_needing_attention: Option<Vec<WireProjectAttentionSummary>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_projects: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub observed: Option<WireObservedWorkspaceSummary>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WireSyncQueueStatus {
    pub queued: u64,
    pub claimed: u64,
    pub waiting_retry: u64,
    pub blocked_offline: u64,
    pub reconciliation_required: u64,
    pub attention: u64,
    pub completed: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WireStaleBaseStatus {
    pub axis: WireFreshnessAxis,
    pub verdict: WireFreshnessVerdict,
    pub summary: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub remedy_command: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub project_path: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub base_snapshot_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub latest_snapshot_id: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WireProjectSetupReadiness {
    pub state: WireProjectSetupReadinessState,
    pub reason: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub remedy: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub identity_hash: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub latest_receipt_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub latest_receipt_state: Option<WireSetupReceiptState>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WireLimitedCapability {
    pub capability: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub support_capability: Option<WireControlPlaneSupportCapability>,
    pub unavailable_because: String,
    pub still_works: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WireRepairCommand {
    pub label: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub command: Option<String>,
    pub mutates: bool,
}
