// Generated by Bowline wire-contract generator 1.2.0. Do not edit.
// Schema SHA-256: 4ba7588109ebc1681e45961ce7cfc67a1cfb121e39447807957b0f64adb3ab98

use serde::{Deserialize, Serialize};

pub const KNOWN_WIRE_CONVERGENCE_READINESS_STATES: &[&str] =
    &["ready", "converging", "recovering", "limited"];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum WireConvergenceReadinessState {
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "converging")]
    Converging,
    #[serde(rename = "recovering")]
    Recovering,
    #[serde(rename = "limited")]
    Limited,
}

impl WireConvergenceReadinessState {
    pub const ALL: &'static [Self] = &[
        Self::Ready,
        Self::Converging,
        Self::Recovering,
        Self::Limited,
    ];

    pub const fn token(self) -> &'static str {
        match self {
            Self::Ready => "ready",
            Self::Converging => "converging",
            Self::Recovering => "recovering",
            Self::Limited => "limited",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "ready" => Some(Self::Ready),
            "converging" => Some(Self::Converging),
            "recovering" => Some(Self::Recovering),
            "limited" => Some(Self::Limited),
            _ => None,
        }
    }
}

pub const KNOWN_WIRE_CONVERGENCE_READINESS_REASONS: &[&str] = &[
    "startup-recovery",
    "causes-pending",
    "attempt-claimed",
    "attempt-waiting-retry",
    "reconciliation-required",
    "recovery-fence-open",
    "filesystem-epoch-open",
    "materialization-incomplete",
    "materialization-conflict",
    "workspace-authority-unpublished",
    "watcher-starting",
    "watcher-recovery-required",
    "observer-connecting",
    "observer-unavailable",
    "attention-required",
];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum WireConvergenceReadinessReason {
    #[serde(rename = "startup-recovery")]
    StartupRecovery,
    #[serde(rename = "causes-pending")]
    CausesPending,
    #[serde(rename = "attempt-claimed")]
    AttemptClaimed,
    #[serde(rename = "attempt-waiting-retry")]
    AttemptWaitingRetry,
    #[serde(rename = "reconciliation-required")]
    ReconciliationRequired,
    #[serde(rename = "recovery-fence-open")]
    RecoveryFenceOpen,
    #[serde(rename = "filesystem-epoch-open")]
    FilesystemEpochOpen,
    #[serde(rename = "materialization-incomplete")]
    MaterializationIncomplete,
    #[serde(rename = "materialization-conflict")]
    MaterializationConflict,
    #[serde(rename = "workspace-authority-unpublished")]
    WorkspaceAuthorityUnpublished,
    #[serde(rename = "watcher-starting")]
    WatcherStarting,
    #[serde(rename = "watcher-recovery-required")]
    WatcherRecoveryRequired,
    #[serde(rename = "observer-connecting")]
    ObserverConnecting,
    #[serde(rename = "observer-unavailable")]
    ObserverUnavailable,
    #[serde(rename = "attention-required")]
    AttentionRequired,
}

impl WireConvergenceReadinessReason {
    pub const ALL: &'static [Self] = &[
        Self::StartupRecovery,
        Self::CausesPending,
        Self::AttemptClaimed,
        Self::AttemptWaitingRetry,
        Self::ReconciliationRequired,
        Self::RecoveryFenceOpen,
        Self::FilesystemEpochOpen,
        Self::MaterializationIncomplete,
        Self::MaterializationConflict,
        Self::WorkspaceAuthorityUnpublished,
        Self::WatcherStarting,
        Self::WatcherRecoveryRequired,
        Self::ObserverConnecting,
        Self::ObserverUnavailable,
        Self::AttentionRequired,
    ];

    pub const fn token(self) -> &'static str {
        match self {
            Self::StartupRecovery => "startup-recovery",
            Self::CausesPending => "causes-pending",
            Self::AttemptClaimed => "attempt-claimed",
            Self::AttemptWaitingRetry => "attempt-waiting-retry",
            Self::ReconciliationRequired => "reconciliation-required",
            Self::RecoveryFenceOpen => "recovery-fence-open",
            Self::FilesystemEpochOpen => "filesystem-epoch-open",
            Self::MaterializationIncomplete => "materialization-incomplete",
            Self::MaterializationConflict => "materialization-conflict",
            Self::WorkspaceAuthorityUnpublished => "workspace-authority-unpublished",
            Self::WatcherStarting => "watcher-starting",
            Self::WatcherRecoveryRequired => "watcher-recovery-required",
            Self::ObserverConnecting => "observer-connecting",
            Self::ObserverUnavailable => "observer-unavailable",
            Self::AttentionRequired => "attention-required",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "startup-recovery" => Some(Self::StartupRecovery),
            "causes-pending" => Some(Self::CausesPending),
            "attempt-claimed" => Some(Self::AttemptClaimed),
            "attempt-waiting-retry" => Some(Self::AttemptWaitingRetry),
            "reconciliation-required" => Some(Self::ReconciliationRequired),
            "recovery-fence-open" => Some(Self::RecoveryFenceOpen),
            "filesystem-epoch-open" => Some(Self::FilesystemEpochOpen),
            "materialization-incomplete" => Some(Self::MaterializationIncomplete),
            "materialization-conflict" => Some(Self::MaterializationConflict),
            "workspace-authority-unpublished" => Some(Self::WorkspaceAuthorityUnpublished),
            "watcher-starting" => Some(Self::WatcherStarting),
            "watcher-recovery-required" => Some(Self::WatcherRecoveryRequired),
            "observer-connecting" => Some(Self::ObserverConnecting),
            "observer-unavailable" => Some(Self::ObserverUnavailable),
            "attention-required" => Some(Self::AttentionRequired),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WireConvergenceStatusSummary {
    pub revision: u64,
    pub state: WireConvergenceReadinessState,
    pub reasons: Vec<WireConvergenceReadinessReason>,
}
