// Generated by Bowline wire-contract generator 1.2.0. Do not edit.
// Schema SHA-256: 90aaff183a675d00a355085f8a588d3d135b786f9e88fb8cde5c8a153078173e

use std::fmt;

use serde::{Deserialize, Deserializer, Serialize, Serializer};

use super::generated::{OpaqueJson, Timestamp, WireStatusCommandOutput};

pub const KNOWN_DAEMON_RPC_ERROR_CODES: &[&str] = &[
    "invalid_request",
    "unsupported_version",
    "method_not_found",
    "malformed_frame",
    "frame_too_large",
    "deadline_exceeded",
    "cancelled",
    "overloaded",
    "resource_exhausted",
    "conflict",
    "not_found",
    "unavailable",
    "permission_denied",
    "internal",
];

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum DaemonRpcErrorCode {
    InvalidRequest,
    UnsupportedVersion,
    MethodNotFound,
    MalformedFrame,
    FrameTooLarge,
    DeadlineExceeded,
    Cancelled,
    Overloaded,
    ResourceExhausted,
    Conflict,
    NotFound,
    Unavailable,
    PermissionDenied,
    Internal,
    Unknown(String),
}

impl DaemonRpcErrorCode {
    pub fn as_str(&self) -> &str {
        match self {
            Self::InvalidRequest => "invalid_request",
            Self::UnsupportedVersion => "unsupported_version",
            Self::MethodNotFound => "method_not_found",
            Self::MalformedFrame => "malformed_frame",
            Self::FrameTooLarge => "frame_too_large",
            Self::DeadlineExceeded => "deadline_exceeded",
            Self::Cancelled => "cancelled",
            Self::Overloaded => "overloaded",
            Self::ResourceExhausted => "resource_exhausted",
            Self::Conflict => "conflict",
            Self::NotFound => "not_found",
            Self::Unavailable => "unavailable",
            Self::PermissionDenied => "permission_denied",
            Self::Internal => "internal",
            Self::Unknown(raw) => raw,
        }
    }
}

impl fmt::Display for DaemonRpcErrorCode {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

impl Serialize for DaemonRpcErrorCode {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for DaemonRpcErrorCode {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let raw = String::deserialize(deserializer)?;
        Ok(match raw.as_str() {
            "invalid_request" => Self::InvalidRequest,
            "unsupported_version" => Self::UnsupportedVersion,
            "method_not_found" => Self::MethodNotFound,
            "malformed_frame" => Self::MalformedFrame,
            "frame_too_large" => Self::FrameTooLarge,
            "deadline_exceeded" => Self::DeadlineExceeded,
            "cancelled" => Self::Cancelled,
            "overloaded" => Self::Overloaded,
            "resource_exhausted" => Self::ResourceExhausted,
            "conflict" => Self::Conflict,
            "not_found" => Self::NotFound,
            "unavailable" => Self::Unavailable,
            "permission_denied" => Self::PermissionDenied,
            "internal" => Self::Internal,
            _ => Self::Unknown(raw),
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DaemonClientHello {
    pub protocol: String,
    pub protocol_version: u16,
    pub contract_version: u16,
    pub schema_hash: String,
    pub client_kind: String,
    pub client_version: String,
    pub capabilities: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DaemonServerHello {
    pub protocol_version: u16,
    pub contract_version: u16,
    pub schema_hash: String,
    pub daemon_version: String,
    pub capabilities: Vec<String>,
    pub instance_id: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DaemonRpcError {
    pub code: DaemonRpcErrorCode,
    pub message: String,
    pub retryable: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub retry_after_ms: Option<u32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub operation_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub required_client_version: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub details: Option<OpaqueJson>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonRpcRequest {
    pub request_id: String,
    pub method: String,
    pub params: OpaqueJson,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deadline_ms: Option<u32>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonRpcResponse {
    pub request_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub result: Option<OpaqueJson>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<DaemonRpcError>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonRpcEvent {
    pub subscription_id: String,
    pub sequence: u64,
    pub event_kind: String,
    pub payload: OpaqueJson,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonRpcCancel {
    pub request_id: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonStatusScopeParams {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub workspace_root: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub project_path: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonStatusSnapshotResult {
    pub instance_id: String,
    pub sequence: u64,
    pub snapshot: WireStatusCommandOutput,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonStatusSubscribeResult {
    pub subscription_id: String,
    pub instance_id: String,
    pub sequence: u64,
    pub snapshot: WireStatusCommandOutput,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonStatusEventPayload {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub snapshot: Option<WireStatusCommandOutput>,
    pub gap: bool,
    pub resync_required: bool,
    pub heartbeat: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonDeviceActionParams {
    pub request_id: String,
    pub idempotency_key: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonSyncRequestParams {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub workspace_root: Option<String>,
    pub idempotency_key: String,
}

pub const KNOWN_DAEMON_SYNC_OPERATION_KINDS: &[&str] = &[
    "daemon-reconcile",
    "conflict-occurrence-reconcile",
    "work-view-overlay-sync",
];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum DaemonSyncOperationKind {
    #[serde(rename = "daemon-reconcile")]
    DaemonReconcile,
    #[serde(rename = "conflict-occurrence-reconcile")]
    ConflictOccurrenceReconcile,
    #[serde(rename = "work-view-overlay-sync")]
    WorkViewOverlaySync,
}

impl DaemonSyncOperationKind {
    pub const ALL: &'static [Self] = &[
        Self::DaemonReconcile,
        Self::ConflictOccurrenceReconcile,
        Self::WorkViewOverlaySync,
    ];

    pub const fn token(self) -> &'static str {
        match self {
            Self::DaemonReconcile => "daemon-reconcile",
            Self::ConflictOccurrenceReconcile => "conflict-occurrence-reconcile",
            Self::WorkViewOverlaySync => "work-view-overlay-sync",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "daemon-reconcile" => Some(Self::DaemonReconcile),
            "conflict-occurrence-reconcile" => Some(Self::ConflictOccurrenceReconcile),
            "work-view-overlay-sync" => Some(Self::WorkViewOverlaySync),
            _ => None,
        }
    }
}

pub const KNOWN_DAEMON_SYNC_RESOURCE_KINDS: &[&str] =
    &["workspace-sync", "conflict-followup", "post-commit"];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum DaemonSyncResourceKind {
    #[serde(rename = "workspace-sync")]
    WorkspaceSync,
    #[serde(rename = "conflict-followup")]
    ConflictFollowup,
    #[serde(rename = "post-commit")]
    PostCommit,
}

impl DaemonSyncResourceKind {
    pub const ALL: &'static [Self] = &[
        Self::WorkspaceSync,
        Self::ConflictFollowup,
        Self::PostCommit,
    ];

    pub const fn token(self) -> &'static str {
        match self {
            Self::WorkspaceSync => "workspace-sync",
            Self::ConflictFollowup => "conflict-followup",
            Self::PostCommit => "post-commit",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "workspace-sync" => Some(Self::WorkspaceSync),
            "conflict-followup" => Some(Self::ConflictFollowup),
            "post-commit" => Some(Self::PostCommit),
            _ => None,
        }
    }
}

pub const KNOWN_DAEMON_SYNC_OPERATION_STATES: &[&str] = &[
    "queued",
    "claimed",
    "waiting_retry",
    "blocked_offline",
    "reconciliation_required",
    "attention",
    "completed",
    "cancelled",
];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum DaemonSyncOperationState {
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "claimed")]
    Claimed,
    #[serde(rename = "waiting_retry")]
    WaitingRetry,
    #[serde(rename = "blocked_offline")]
    BlockedOffline,
    #[serde(rename = "reconciliation_required")]
    ReconciliationRequired,
    #[serde(rename = "attention")]
    Attention,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "cancelled")]
    Cancelled,
}

impl DaemonSyncOperationState {
    pub const ALL: &'static [Self] = &[
        Self::Queued,
        Self::Claimed,
        Self::WaitingRetry,
        Self::BlockedOffline,
        Self::ReconciliationRequired,
        Self::Attention,
        Self::Completed,
        Self::Cancelled,
    ];

    pub const fn token(self) -> &'static str {
        match self {
            Self::Queued => "queued",
            Self::Claimed => "claimed",
            Self::WaitingRetry => "waiting_retry",
            Self::BlockedOffline => "blocked_offline",
            Self::ReconciliationRequired => "reconciliation_required",
            Self::Attention => "attention",
            Self::Completed => "completed",
            Self::Cancelled => "cancelled",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "queued" => Some(Self::Queued),
            "claimed" => Some(Self::Claimed),
            "waiting_retry" => Some(Self::WaitingRetry),
            "blocked_offline" => Some(Self::BlockedOffline),
            "reconciliation_required" => Some(Self::ReconciliationRequired),
            "attention" => Some(Self::Attention),
            "completed" => Some(Self::Completed),
            "cancelled" => Some(Self::Cancelled),
            _ => None,
        }
    }
}

pub const KNOWN_DAEMON_SYNC_OPERATION_OWNERSHIPS: &[&str] = &[
    "unclaimed",
    "owned-by-this-daemon",
    "owned-by-another-daemon",
    "lease-expired",
];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum DaemonSyncOperationOwnership {
    #[serde(rename = "unclaimed")]
    Unclaimed,
    #[serde(rename = "owned-by-this-daemon")]
    OwnedByThisDaemon,
    #[serde(rename = "owned-by-another-daemon")]
    OwnedByAnotherDaemon,
    #[serde(rename = "lease-expired")]
    LeaseExpired,
}

impl DaemonSyncOperationOwnership {
    pub const ALL: &'static [Self] = &[
        Self::Unclaimed,
        Self::OwnedByThisDaemon,
        Self::OwnedByAnotherDaemon,
        Self::LeaseExpired,
    ];

    pub const fn token(self) -> &'static str {
        match self {
            Self::Unclaimed => "unclaimed",
            Self::OwnedByThisDaemon => "owned-by-this-daemon",
            Self::OwnedByAnotherDaemon => "owned-by-another-daemon",
            Self::LeaseExpired => "lease-expired",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "unclaimed" => Some(Self::Unclaimed),
            "owned-by-this-daemon" => Some(Self::OwnedByThisDaemon),
            "owned-by-another-daemon" => Some(Self::OwnedByAnotherDaemon),
            "lease-expired" => Some(Self::LeaseExpired),
            _ => None,
        }
    }
}

pub const KNOWN_DAEMON_SYNC_CANCELLATION_OUTCOMES: &[&str] = &[
    "requested",
    "cancelled",
    "already-completed",
    "already-cancelled",
];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum DaemonSyncCancellationOutcome {
    #[serde(rename = "requested")]
    Requested,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "already-completed")]
    AlreadyCompleted,
    #[serde(rename = "already-cancelled")]
    AlreadyCancelled,
}

impl DaemonSyncCancellationOutcome {
    pub const ALL: &'static [Self] = &[
        Self::Requested,
        Self::Cancelled,
        Self::AlreadyCompleted,
        Self::AlreadyCancelled,
    ];

    pub const fn token(self) -> &'static str {
        match self {
            Self::Requested => "requested",
            Self::Cancelled => "cancelled",
            Self::AlreadyCompleted => "already-completed",
            Self::AlreadyCancelled => "already-cancelled",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "requested" => Some(Self::Requested),
            "cancelled" => Some(Self::Cancelled),
            "already-completed" => Some(Self::AlreadyCompleted),
            "already-cancelled" => Some(Self::AlreadyCancelled),
            _ => None,
        }
    }
}

pub const KNOWN_DAEMON_SYNC_REQUEST_OUTCOMES: &[&str] = &["enqueued", "coalesced"];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum DaemonSyncRequestOutcome {
    #[serde(rename = "enqueued")]
    Enqueued,
    #[serde(rename = "coalesced")]
    Coalesced,
}

impl DaemonSyncRequestOutcome {
    pub const ALL: &'static [Self] = &[Self::Enqueued, Self::Coalesced];

    pub const fn token(self) -> &'static str {
        match self {
            Self::Enqueued => "enqueued",
            Self::Coalesced => "coalesced",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "enqueued" => Some(Self::Enqueued),
            "coalesced" => Some(Self::Coalesced),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonSyncResource {
    pub kind: DaemonSyncResourceKind,
    pub workspace_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conflict_id: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonOperationResult {
    pub operation_id: String,
    pub kind: DaemonSyncOperationKind,
    pub resource: DaemonSyncResource,
    pub state: DaemonSyncOperationState,
    pub attempt_count: u32,
    pub claim_generation: u64,
    pub ownership: DaemonSyncOperationOwnership,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub claimed_by: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lease_expires_at: Option<Timestamp>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cancellation_requested_at: Option<Timestamp>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_attempt_at: Option<Timestamp>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub result: Option<OpaqueJson>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_error_code: Option<String>,
    pub created_at: Timestamp,
    pub updated_at: Timestamp,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonSyncRequestResult {
    pub outcome: DaemonSyncRequestOutcome,
    pub operation: DaemonOperationResult,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonCancelOperationParams {
    pub operation_id: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonCancelOperationResult {
    pub outcome: DaemonSyncCancellationOutcome,
    pub operation: DaemonOperationResult,
}
