// Generated by Bowline wire-contract generator 1.2.0. Do not edit.
// Schema SHA-256: 4ba7588109ebc1681e45961ce7cfc67a1cfb121e39447807957b0f64adb3ab98

use super::generated::{
    CommandName, EventName, EventSeverity, WireRepairCommand, WireStatusCommandOutput,
};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WireEventWatermarks {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_scan_at: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_event_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub event_lag_ms: Option<u64>,
}

pub const KNOWN_WIRE_EVENT_SUBJECT_KINDS: &[&str] = &[
    "workspace",
    "root",
    "project",
    "path",
    "snapshot",
    "content",
    "pack",
    "policy",
    "env-record",
    "setup-receipt",
    "conflict",
    "work-view",
    "lease",
    "overlay",
    "device",
    "metadata",
    "component",
];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum WireEventSubjectKind {
    #[serde(rename = "workspace")]
    Workspace,
    #[serde(rename = "root")]
    Root,
    #[serde(rename = "project")]
    Project,
    #[serde(rename = "path")]
    Path,
    #[serde(rename = "snapshot")]
    Snapshot,
    #[serde(rename = "content")]
    Content,
    #[serde(rename = "pack")]
    Pack,
    #[serde(rename = "policy")]
    Policy,
    #[serde(rename = "env-record")]
    EnvRecord,
    #[serde(rename = "setup-receipt")]
    SetupReceipt,
    #[serde(rename = "conflict")]
    Conflict,
    #[serde(rename = "work-view")]
    WorkView,
    #[serde(rename = "lease")]
    Lease,
    #[serde(rename = "overlay")]
    Overlay,
    #[serde(rename = "device")]
    Device,
    #[serde(rename = "metadata")]
    Metadata,
    #[serde(rename = "component")]
    Component,
}

impl WireEventSubjectKind {
    pub const ALL: &'static [Self] = &[
        Self::Workspace,
        Self::Root,
        Self::Project,
        Self::Path,
        Self::Snapshot,
        Self::Content,
        Self::Pack,
        Self::Policy,
        Self::EnvRecord,
        Self::SetupReceipt,
        Self::Conflict,
        Self::WorkView,
        Self::Lease,
        Self::Overlay,
        Self::Device,
        Self::Metadata,
        Self::Component,
    ];

    pub const fn token(self) -> &'static str {
        match self {
            Self::Workspace => "workspace",
            Self::Root => "root",
            Self::Project => "project",
            Self::Path => "path",
            Self::Snapshot => "snapshot",
            Self::Content => "content",
            Self::Pack => "pack",
            Self::Policy => "policy",
            Self::EnvRecord => "env-record",
            Self::SetupReceipt => "setup-receipt",
            Self::Conflict => "conflict",
            Self::WorkView => "work-view",
            Self::Lease => "lease",
            Self::Overlay => "overlay",
            Self::Device => "device",
            Self::Metadata => "metadata",
            Self::Component => "component",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "workspace" => Some(Self::Workspace),
            "root" => Some(Self::Root),
            "project" => Some(Self::Project),
            "path" => Some(Self::Path),
            "snapshot" => Some(Self::Snapshot),
            "content" => Some(Self::Content),
            "pack" => Some(Self::Pack),
            "policy" => Some(Self::Policy),
            "env-record" => Some(Self::EnvRecord),
            "setup-receipt" => Some(Self::SetupReceipt),
            "conflict" => Some(Self::Conflict),
            "work-view" => Some(Self::WorkView),
            "lease" => Some(Self::Lease),
            "overlay" => Some(Self::Overlay),
            "device" => Some(Self::Device),
            "metadata" => Some(Self::Metadata),
            "component" => Some(Self::Component),
            _ => None,
        }
    }
}

pub const KNOWN_WIRE_EVENT_ACTOR_KINDS: &[&str] = &["system", "daemon", "device", "agent", "user"];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum WireEventActorKind {
    #[serde(rename = "system")]
    System,
    #[serde(rename = "daemon")]
    Daemon,
    #[serde(rename = "device")]
    Device,
    #[serde(rename = "agent")]
    Agent,
    #[serde(rename = "user")]
    User,
}

impl WireEventActorKind {
    pub const ALL: &'static [Self] = &[
        Self::System,
        Self::Daemon,
        Self::Device,
        Self::Agent,
        Self::User,
    ];

    pub const fn token(self) -> &'static str {
        match self {
            Self::System => "system",
            Self::Daemon => "daemon",
            Self::Device => "device",
            Self::Agent => "agent",
            Self::User => "user",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "system" => Some(Self::System),
            "daemon" => Some(Self::Daemon),
            "device" => Some(Self::Device),
            "agent" => Some(Self::Agent),
            "user" => Some(Self::User),
            _ => None,
        }
    }
}

pub const KNOWN_WIRE_COMMAND_RECOVERABILITIES: &[&str] =
    &["retry", "user-action", "unsupported", "none"];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum WireCommandRecoverability {
    #[serde(rename = "retry")]
    Retry,
    #[serde(rename = "user-action")]
    UserAction,
    #[serde(rename = "unsupported")]
    Unsupported,
    #[serde(rename = "none")]
    None,
}

impl WireCommandRecoverability {
    pub const ALL: &'static [Self] =
        &[Self::Retry, Self::UserAction, Self::Unsupported, Self::None];

    pub const fn token(self) -> &'static str {
        match self {
            Self::Retry => "retry",
            Self::UserAction => "user-action",
            Self::Unsupported => "unsupported",
            Self::None => "none",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "retry" => Some(Self::Retry),
            "user-action" => Some(Self::UserAction),
            "unsupported" => Some(Self::Unsupported),
            "none" => Some(Self::None),
            _ => None,
        }
    }
}

pub const KNOWN_WIRE_COMMAND_ERROR_STATUSS: &[&str] =
    &["usage-error", "unsupported", "limited", "failed"];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum WireCommandErrorStatus {
    #[serde(rename = "usage-error")]
    UsageError,
    #[serde(rename = "unsupported")]
    Unsupported,
    #[serde(rename = "limited")]
    Limited,
    #[serde(rename = "failed")]
    Failed,
}

impl WireCommandErrorStatus {
    pub const ALL: &'static [Self] = &[
        Self::UsageError,
        Self::Unsupported,
        Self::Limited,
        Self::Failed,
    ];

    pub const fn token(self) -> &'static str {
        match self {
            Self::UsageError => "usage-error",
            Self::Unsupported => "unsupported",
            Self::Limited => "limited",
            Self::Failed => "failed",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "usage-error" => Some(Self::UsageError),
            "unsupported" => Some(Self::Unsupported),
            "limited" => Some(Self::Limited),
            "failed" => Some(Self::Failed),
            _ => None,
        }
    }
}

pub const KNOWN_WIRE_EVENT_REDACTION_STATUSS: &[&str] = &["not-needed", "applied"];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum WireEventRedactionStatus {
    #[serde(rename = "not-needed")]
    NotNeeded,
    #[serde(rename = "applied")]
    Applied,
}

impl WireEventRedactionStatus {
    pub const ALL: &'static [Self] = &[Self::NotNeeded, Self::Applied];

    pub const fn token(self) -> &'static str {
        match self {
            Self::NotNeeded => "not-needed",
            Self::Applied => "applied",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "not-needed" => Some(Self::NotNeeded),
            "applied" => Some(Self::Applied),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WireEventSubject {
    pub kind: WireEventSubjectKind,
    pub id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WireEventActor {
    pub kind: WireEventActorKind,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WireEventRedaction {
    pub status: WireEventRedactionStatus,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rules: Option<Vec<String>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WireCommandError {
    pub code: String,
    pub message: String,
    pub recoverability: WireCommandRecoverability,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub remediation: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub details: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub retry_after_seconds: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub correlation_id: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WireCommandErrorOutput {
    pub contract_version: u16,
    pub command: CommandName,
    pub generated_at: String,
    pub status: WireCommandErrorStatus,
    pub error: WireCommandError,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_actions: Option<Vec<WireRepairCommand>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WireWatchWorkspaceEvent {
    pub schema_version: u16,
    pub id: String,
    pub name: EventName,
    pub occurred_at: String,
    pub severity: EventSeverity,
    pub summary: String,
    pub workspace_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lease_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub device_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subject: Option<WireEventSubject>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actor: Option<WireEventActor>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payload: Option<BTreeMap<String, serde_json::Value>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub causation_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub correlation_id: Option<String>,
    pub redaction: WireEventRedaction,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WireWatchStatusFrame {
    pub contract_version: u16,
    pub sequence: u64,
    pub generated_at: String,
    pub workspace_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
    pub status: WireStatusCommandOutput,
    pub watermark: WireEventWatermarks,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_event_id: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WireWatchEventFrame {
    pub contract_version: u16,
    pub sequence: u64,
    pub generated_at: String,
    pub workspace_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
    pub event: WireWatchWorkspaceEvent,
    pub watermark: WireEventWatermarks,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WireWatchErrorFrame {
    pub contract_version: u16,
    pub sequence: u64,
    pub generated_at: String,
    pub workspace_id: String,
    pub error: WireCommandErrorOutput,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum WireWatchFrame {
    #[serde(rename = "status")]
    Status(Box<WireWatchStatusFrame>),
    #[serde(rename = "event")]
    Event(Box<WireWatchEventFrame>),
    #[serde(rename = "error")]
    Error(Box<WireWatchErrorFrame>),
}
