// Generated by Bowline wire-contract generator 1.2.0. Do not edit.
// Schema SHA-256: 90aaff183a675d00a355085f8a588d3d135b786f9e88fb8cde5c8a153078173e

use super::generated::{
    DeviceApprovalAffordance, StatusSummary, Timestamp, WireEventWatermarks, WireFreshnessVerdict,
    WireLimitedCapability, WireProjectSetupReadiness, WireRepairCommand, WireStaleBaseStatus,
    WireStatusItem, WireStatusScope, WireSyncQueueStatus, WireWorkspaceStatus,
    WireWorkspaceSummary,
};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WireStatusCommandOutput {
    pub contract_version: u16,
    pub command: String,
    pub generated_at: Timestamp,
    pub workspace_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub device_approvals: Option<Vec<DeviceApprovalAffordance>>,
    pub status: WireWorkspaceStatus,
    pub status_summary: StatusSummary,
    pub items: Vec<WireStatusItem>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scope: Option<WireStatusScope>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requested_path: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resolved_workspace_root: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub workspace_summary: Option<WireWorkspaceSummary>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub setup_readiness: Option<WireProjectSetupReadiness>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sync_queue: Option<WireSyncQueueStatus>,
    pub freshness: WireFreshnessVerdict,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stale_bases: Option<Vec<WireStaleBaseStatus>>,
    pub limits: Vec<WireLimitedCapability>,
    pub event_watermarks: WireEventWatermarks,
    pub next_actions: Vec<WireRepairCommand>,
}
