// Generated by Bowline wire-contract generator 1.2.0. Do not edit.
// Schema SHA-256: 90aaff183a675d00a355085f8a588d3d135b786f9e88fb8cde5c8a153078173e

use std::{collections::BTreeMap, fmt};

use serde::{Deserialize, Deserializer, Serialize, Serializer};

pub use super::{
    generated_daemon_rpc::*, generated_status::*, generated_status_output::*,
    generated_status_output_support::*, generated_status_transport::*, generated_watch::*,
};

pub const WIRE_SCHEMA_HASH: &str =
    "90aaff183a675d00a355085f8a588d3d135b786f9e88fb8cde5c8a153078173e";
pub const MACHINE_CONTRACT_VERSION: u16 = 8;

pub type Timestamp = String;

pub type OpaqueJson = serde_json::Value;

pub type MachineContractVersion = u16;

pub const KNOWN_EVENT_NAMES: &[&str] = &[
    "namespace.created",
    "namespace.moved",
    "namespace.deleted_or_archived",
    "hydration.started",
    "hydration.completed",
    "hydration.blocked",
    "policy.classified",
    "policy.needs_approval",
    "policy.changed",
    "env.imported",
    "env.materialized",
    "env.revoked",
    "setup.started",
    "setup.completed",
    "setup.blocked",
    "source.stale",
    "work.created",
    "work.updated",
    "work.review_ready",
    "work.accepted",
    "work.discarded",
    "work.restored",
    "work.cleanup_previewed",
    "work.cleanup_completed",
    "lease.created",
    "lease.updated",
    "lease.dispatched",
    "lease.claimed",
    "lease.completed",
    "lease.cancelled",
    "lease.extended",
    "lease.review_ready",
    "overlay.changed",
    "conflict.created",
    "conflict.bundle_created",
    "conflict.resolution_proposed",
    "conflict.resolution_accepted",
    "conflict.resolution_rejected",
    "merge.plugin_applied",
    "daemon.degraded",
    "daemon.recovered",
    "device.approval_requested",
    "device.approved",
    "device.denied",
    "device.revoked",
    "recovery_key.created",
    "recovery_key.verified",
    "recovery_key.rotated",
    "recovery_key.revoked",
    "auth.login_started",
    "auth.login_completed",
    "sync.started",
    "sync.completed",
    "sync.limited",
    "sync.degraded",
    "sync.stat_cache_divergence",
    "sync.recovered",
    "watcher.degraded",
    "watcher.recovered",
    "network.offline",
    "network.recovered",
    "metadata.corrupt",
];

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum EventName {
    NamespaceCreated,
    NamespaceMoved,
    NamespaceDeletedOrArchived,
    HydrationStarted,
    HydrationCompleted,
    HydrationBlocked,
    PolicyClassified,
    PolicyNeedsApproval,
    PolicyChanged,
    EnvImported,
    EnvMaterialized,
    EnvRevoked,
    SetupStarted,
    SetupCompleted,
    SetupBlocked,
    SourceStale,
    WorkCreated,
    WorkUpdated,
    WorkReviewReady,
    WorkAccepted,
    WorkDiscarded,
    WorkRestored,
    WorkCleanupPreviewed,
    WorkCleanupCompleted,
    LeaseCreated,
    LeaseUpdated,
    LeaseDispatched,
    LeaseClaimed,
    LeaseCompleted,
    LeaseCancelled,
    LeaseExtended,
    LeaseReviewReady,
    OverlayChanged,
    ConflictCreated,
    ConflictBundleCreated,
    ConflictResolutionProposed,
    ConflictResolutionAccepted,
    ConflictResolutionRejected,
    MergePluginApplied,
    DaemonDegraded,
    DaemonRecovered,
    DeviceApprovalRequested,
    DeviceApproved,
    DeviceDenied,
    DeviceRevoked,
    RecoveryKeyCreated,
    RecoveryKeyVerified,
    RecoveryKeyRotated,
    RecoveryKeyRevoked,
    AuthLoginStarted,
    AuthLoginCompleted,
    SyncStarted,
    SyncCompleted,
    SyncLimited,
    SyncDegraded,
    StatCacheDivergence,
    SyncRecovered,
    WatcherDegraded,
    WatcherRecovered,
    NetworkOffline,
    NetworkRecovered,
    MetadataCorrupt,
    Unknown(String),
}

impl EventName {
    pub fn as_str(&self) -> &str {
        match self {
            Self::NamespaceCreated => "namespace.created",
            Self::NamespaceMoved => "namespace.moved",
            Self::NamespaceDeletedOrArchived => "namespace.deleted_or_archived",
            Self::HydrationStarted => "hydration.started",
            Self::HydrationCompleted => "hydration.completed",
            Self::HydrationBlocked => "hydration.blocked",
            Self::PolicyClassified => "policy.classified",
            Self::PolicyNeedsApproval => "policy.needs_approval",
            Self::PolicyChanged => "policy.changed",
            Self::EnvImported => "env.imported",
            Self::EnvMaterialized => "env.materialized",
            Self::EnvRevoked => "env.revoked",
            Self::SetupStarted => "setup.started",
            Self::SetupCompleted => "setup.completed",
            Self::SetupBlocked => "setup.blocked",
            Self::SourceStale => "source.stale",
            Self::WorkCreated => "work.created",
            Self::WorkUpdated => "work.updated",
            Self::WorkReviewReady => "work.review_ready",
            Self::WorkAccepted => "work.accepted",
            Self::WorkDiscarded => "work.discarded",
            Self::WorkRestored => "work.restored",
            Self::WorkCleanupPreviewed => "work.cleanup_previewed",
            Self::WorkCleanupCompleted => "work.cleanup_completed",
            Self::LeaseCreated => "lease.created",
            Self::LeaseUpdated => "lease.updated",
            Self::LeaseDispatched => "lease.dispatched",
            Self::LeaseClaimed => "lease.claimed",
            Self::LeaseCompleted => "lease.completed",
            Self::LeaseCancelled => "lease.cancelled",
            Self::LeaseExtended => "lease.extended",
            Self::LeaseReviewReady => "lease.review_ready",
            Self::OverlayChanged => "overlay.changed",
            Self::ConflictCreated => "conflict.created",
            Self::ConflictBundleCreated => "conflict.bundle_created",
            Self::ConflictResolutionProposed => "conflict.resolution_proposed",
            Self::ConflictResolutionAccepted => "conflict.resolution_accepted",
            Self::ConflictResolutionRejected => "conflict.resolution_rejected",
            Self::MergePluginApplied => "merge.plugin_applied",
            Self::DaemonDegraded => "daemon.degraded",
            Self::DaemonRecovered => "daemon.recovered",
            Self::DeviceApprovalRequested => "device.approval_requested",
            Self::DeviceApproved => "device.approved",
            Self::DeviceDenied => "device.denied",
            Self::DeviceRevoked => "device.revoked",
            Self::RecoveryKeyCreated => "recovery_key.created",
            Self::RecoveryKeyVerified => "recovery_key.verified",
            Self::RecoveryKeyRotated => "recovery_key.rotated",
            Self::RecoveryKeyRevoked => "recovery_key.revoked",
            Self::AuthLoginStarted => "auth.login_started",
            Self::AuthLoginCompleted => "auth.login_completed",
            Self::SyncStarted => "sync.started",
            Self::SyncCompleted => "sync.completed",
            Self::SyncLimited => "sync.limited",
            Self::SyncDegraded => "sync.degraded",
            Self::StatCacheDivergence => "sync.stat_cache_divergence",
            Self::SyncRecovered => "sync.recovered",
            Self::WatcherDegraded => "watcher.degraded",
            Self::WatcherRecovered => "watcher.recovered",
            Self::NetworkOffline => "network.offline",
            Self::NetworkRecovered => "network.recovered",
            Self::MetadataCorrupt => "metadata.corrupt",
            Self::Unknown(raw) => raw,
        }
    }
}

impl fmt::Display for EventName {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

impl Serialize for EventName {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for EventName {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let raw = String::deserialize(deserializer)?;
        Ok(match raw.as_str() {
            "namespace.created" => Self::NamespaceCreated,
            "namespace.moved" => Self::NamespaceMoved,
            "namespace.deleted_or_archived" => Self::NamespaceDeletedOrArchived,
            "hydration.started" => Self::HydrationStarted,
            "hydration.completed" => Self::HydrationCompleted,
            "hydration.blocked" => Self::HydrationBlocked,
            "policy.classified" => Self::PolicyClassified,
            "policy.needs_approval" => Self::PolicyNeedsApproval,
            "policy.changed" => Self::PolicyChanged,
            "env.imported" => Self::EnvImported,
            "env.materialized" => Self::EnvMaterialized,
            "env.revoked" => Self::EnvRevoked,
            "setup.started" => Self::SetupStarted,
            "setup.completed" => Self::SetupCompleted,
            "setup.blocked" => Self::SetupBlocked,
            "source.stale" => Self::SourceStale,
            "work.created" => Self::WorkCreated,
            "work.updated" => Self::WorkUpdated,
            "work.review_ready" => Self::WorkReviewReady,
            "work.accepted" => Self::WorkAccepted,
            "work.discarded" => Self::WorkDiscarded,
            "work.restored" => Self::WorkRestored,
            "work.cleanup_previewed" => Self::WorkCleanupPreviewed,
            "work.cleanup_completed" => Self::WorkCleanupCompleted,
            "lease.created" => Self::LeaseCreated,
            "lease.updated" => Self::LeaseUpdated,
            "lease.dispatched" => Self::LeaseDispatched,
            "lease.claimed" => Self::LeaseClaimed,
            "lease.completed" => Self::LeaseCompleted,
            "lease.cancelled" => Self::LeaseCancelled,
            "lease.extended" => Self::LeaseExtended,
            "lease.review_ready" => Self::LeaseReviewReady,
            "overlay.changed" => Self::OverlayChanged,
            "conflict.created" => Self::ConflictCreated,
            "conflict.bundle_created" => Self::ConflictBundleCreated,
            "conflict.resolution_proposed" => Self::ConflictResolutionProposed,
            "conflict.resolution_accepted" => Self::ConflictResolutionAccepted,
            "conflict.resolution_rejected" => Self::ConflictResolutionRejected,
            "merge.plugin_applied" => Self::MergePluginApplied,
            "daemon.degraded" => Self::DaemonDegraded,
            "daemon.recovered" => Self::DaemonRecovered,
            "device.approval_requested" => Self::DeviceApprovalRequested,
            "device.approved" => Self::DeviceApproved,
            "device.denied" => Self::DeviceDenied,
            "device.revoked" => Self::DeviceRevoked,
            "recovery_key.created" => Self::RecoveryKeyCreated,
            "recovery_key.verified" => Self::RecoveryKeyVerified,
            "recovery_key.rotated" => Self::RecoveryKeyRotated,
            "recovery_key.revoked" => Self::RecoveryKeyRevoked,
            "auth.login_started" => Self::AuthLoginStarted,
            "auth.login_completed" => Self::AuthLoginCompleted,
            "sync.started" => Self::SyncStarted,
            "sync.completed" => Self::SyncCompleted,
            "sync.limited" => Self::SyncLimited,
            "sync.degraded" => Self::SyncDegraded,
            "sync.stat_cache_divergence" => Self::StatCacheDivergence,
            "sync.recovered" => Self::SyncRecovered,
            "watcher.degraded" => Self::WatcherDegraded,
            "watcher.recovered" => Self::WatcherRecovered,
            "network.offline" => Self::NetworkOffline,
            "network.recovered" => Self::NetworkRecovered,
            "metadata.corrupt" => Self::MetadataCorrupt,
            _ => Self::Unknown(raw),
        })
    }
}

pub const KNOWN_EVENT_SEVERITIES: &[&str] = &["info", "attention", "limited"];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum EventSeverity {
    #[serde(rename = "info")]
    Info,
    #[serde(rename = "attention")]
    Attention,
    #[serde(rename = "limited")]
    Limited,
}

impl EventSeverity {
    pub const ALL: &'static [Self] = &[Self::Info, Self::Attention, Self::Limited];

    pub const fn token(self) -> &'static str {
        match self {
            Self::Info => "info",
            Self::Attention => "attention",
            Self::Limited => "limited",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "info" => Some(Self::Info),
            "attention" => Some(Self::Attention),
            "limited" => Some(Self::Limited),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WireWorkspaceEvent {
    pub schema_version: u16,
    pub id: String,
    pub name: EventName,
    pub occurred_at: Timestamp,
    pub severity: EventSeverity,
    pub summary: String,
    pub workspace_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payload: Option<BTreeMap<String, serde_json::Value>>,
}

pub const KNOWN_COMMAND_NAMES: &[&str] = &[
    "help",
    "version",
    "contract",
    "mcp",
    "update",
    "unknown",
    "login",
    "logout",
    "device approve",
    "device deny",
    "device revoke",
    "recover",
    "setup",
    "status",
    "device list",
    "device request",
    "device accept",
    "events",
    "history",
    "tui",
    "resolve",
    "forget-local",
    "archive",
    "purge",
    "work create",
    "work review",
    "work list",
    "work diff",
    "work accept",
    "work discard",
    "work restore",
    "work cleanup",
    "agent context",
    "agent start",
    "agent prompt",
    "agent complete",
    "agent cancel",
    "agent extend",
    "agent mcp-token",
    "lease join",
    "daemon start",
    "daemon stop",
    "daemon status",
    "daemon install",
    "daemon restart",
    "daemon uninstall",
    "diagnostics collect",
    "connect",
    "handoff",
];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum CommandName {
    #[serde(rename = "help")]
    Help,
    #[serde(rename = "version")]
    Version,
    #[serde(rename = "contract")]
    Contract,
    #[serde(rename = "mcp")]
    Mcp,
    #[serde(rename = "update")]
    Update,
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "login")]
    Login,
    #[serde(rename = "logout")]
    Logout,
    #[serde(rename = "device approve")]
    Approve,
    #[serde(rename = "device deny")]
    Deny,
    #[serde(rename = "device revoke")]
    Revoke,
    #[serde(rename = "recover")]
    Recover,
    #[serde(rename = "setup")]
    Setup,
    #[serde(rename = "status")]
    Status,
    #[serde(rename = "device list")]
    Devices,
    #[serde(rename = "device request")]
    DeviceRequest,
    #[serde(rename = "device accept")]
    DeviceAccept,
    #[serde(rename = "events")]
    Events,
    #[serde(rename = "history")]
    History,
    #[serde(rename = "tui")]
    Tui,
    #[serde(rename = "resolve")]
    Resolve,
    #[serde(rename = "forget-local")]
    ForgetLocal,
    #[serde(rename = "archive")]
    Archive,
    #[serde(rename = "purge")]
    Purge,
    #[serde(rename = "work create")]
    WorkCreate,
    #[serde(rename = "work review")]
    Review,
    #[serde(rename = "work list")]
    Work,
    #[serde(rename = "work diff")]
    Diff,
    #[serde(rename = "work accept")]
    Accept,
    #[serde(rename = "work discard")]
    Discard,
    #[serde(rename = "work restore")]
    Restore,
    #[serde(rename = "work cleanup")]
    Cleanup,
    #[serde(rename = "agent context")]
    AgentContext,
    #[serde(rename = "agent start")]
    AgentStart,
    #[serde(rename = "agent prompt")]
    AgentPrompt,
    #[serde(rename = "agent complete")]
    AgentComplete,
    #[serde(rename = "agent cancel")]
    AgentCancel,
    #[serde(rename = "agent extend")]
    AgentExtend,
    #[serde(rename = "agent mcp-token")]
    AgentMcpToken,
    #[serde(rename = "lease join")]
    LeaseJoin,
    #[serde(rename = "daemon start")]
    DaemonStart,
    #[serde(rename = "daemon stop")]
    DaemonStop,
    #[serde(rename = "daemon status")]
    DaemonStatus,
    #[serde(rename = "daemon install")]
    DaemonInstall,
    #[serde(rename = "daemon restart")]
    DaemonRestart,
    #[serde(rename = "daemon uninstall")]
    DaemonUninstall,
    #[serde(rename = "diagnostics collect")]
    DiagnosticsCollect,
    #[serde(rename = "connect")]
    Connect,
    #[serde(rename = "handoff")]
    Handoff,
}

impl CommandName {
    pub const ALL: &'static [Self] = &[
        Self::Help,
        Self::Version,
        Self::Contract,
        Self::Mcp,
        Self::Update,
        Self::Unknown,
        Self::Login,
        Self::Logout,
        Self::Approve,
        Self::Deny,
        Self::Revoke,
        Self::Recover,
        Self::Setup,
        Self::Status,
        Self::Devices,
        Self::DeviceRequest,
        Self::DeviceAccept,
        Self::Events,
        Self::History,
        Self::Tui,
        Self::Resolve,
        Self::ForgetLocal,
        Self::Archive,
        Self::Purge,
        Self::WorkCreate,
        Self::Review,
        Self::Work,
        Self::Diff,
        Self::Accept,
        Self::Discard,
        Self::Restore,
        Self::Cleanup,
        Self::AgentContext,
        Self::AgentStart,
        Self::AgentPrompt,
        Self::AgentComplete,
        Self::AgentCancel,
        Self::AgentExtend,
        Self::AgentMcpToken,
        Self::LeaseJoin,
        Self::DaemonStart,
        Self::DaemonStop,
        Self::DaemonStatus,
        Self::DaemonInstall,
        Self::DaemonRestart,
        Self::DaemonUninstall,
        Self::DiagnosticsCollect,
        Self::Connect,
        Self::Handoff,
    ];

    pub const fn token(self) -> &'static str {
        match self {
            Self::Help => "help",
            Self::Version => "version",
            Self::Contract => "contract",
            Self::Mcp => "mcp",
            Self::Update => "update",
            Self::Unknown => "unknown",
            Self::Login => "login",
            Self::Logout => "logout",
            Self::Approve => "device approve",
            Self::Deny => "device deny",
            Self::Revoke => "device revoke",
            Self::Recover => "recover",
            Self::Setup => "setup",
            Self::Status => "status",
            Self::Devices => "device list",
            Self::DeviceRequest => "device request",
            Self::DeviceAccept => "device accept",
            Self::Events => "events",
            Self::History => "history",
            Self::Tui => "tui",
            Self::Resolve => "resolve",
            Self::ForgetLocal => "forget-local",
            Self::Archive => "archive",
            Self::Purge => "purge",
            Self::WorkCreate => "work create",
            Self::Review => "work review",
            Self::Work => "work list",
            Self::Diff => "work diff",
            Self::Accept => "work accept",
            Self::Discard => "work discard",
            Self::Restore => "work restore",
            Self::Cleanup => "work cleanup",
            Self::AgentContext => "agent context",
            Self::AgentStart => "agent start",
            Self::AgentPrompt => "agent prompt",
            Self::AgentComplete => "agent complete",
            Self::AgentCancel => "agent cancel",
            Self::AgentExtend => "agent extend",
            Self::AgentMcpToken => "agent mcp-token",
            Self::LeaseJoin => "lease join",
            Self::DaemonStart => "daemon start",
            Self::DaemonStop => "daemon stop",
            Self::DaemonStatus => "daemon status",
            Self::DaemonInstall => "daemon install",
            Self::DaemonRestart => "daemon restart",
            Self::DaemonUninstall => "daemon uninstall",
            Self::DiagnosticsCollect => "diagnostics collect",
            Self::Connect => "connect",
            Self::Handoff => "handoff",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "help" => Some(Self::Help),
            "version" => Some(Self::Version),
            "contract" => Some(Self::Contract),
            "mcp" => Some(Self::Mcp),
            "update" => Some(Self::Update),
            "unknown" => Some(Self::Unknown),
            "login" => Some(Self::Login),
            "logout" => Some(Self::Logout),
            "device approve" => Some(Self::Approve),
            "device deny" => Some(Self::Deny),
            "device revoke" => Some(Self::Revoke),
            "recover" => Some(Self::Recover),
            "setup" => Some(Self::Setup),
            "status" => Some(Self::Status),
            "device list" => Some(Self::Devices),
            "device request" => Some(Self::DeviceRequest),
            "device accept" => Some(Self::DeviceAccept),
            "events" => Some(Self::Events),
            "history" => Some(Self::History),
            "tui" => Some(Self::Tui),
            "resolve" => Some(Self::Resolve),
            "forget-local" => Some(Self::ForgetLocal),
            "archive" => Some(Self::Archive),
            "purge" => Some(Self::Purge),
            "work create" => Some(Self::WorkCreate),
            "work review" => Some(Self::Review),
            "work list" => Some(Self::Work),
            "work diff" => Some(Self::Diff),
            "work accept" => Some(Self::Accept),
            "work discard" => Some(Self::Discard),
            "work restore" => Some(Self::Restore),
            "work cleanup" => Some(Self::Cleanup),
            "agent context" => Some(Self::AgentContext),
            "agent start" => Some(Self::AgentStart),
            "agent prompt" => Some(Self::AgentPrompt),
            "agent complete" => Some(Self::AgentComplete),
            "agent cancel" => Some(Self::AgentCancel),
            "agent extend" => Some(Self::AgentExtend),
            "agent mcp-token" => Some(Self::AgentMcpToken),
            "lease join" => Some(Self::LeaseJoin),
            "daemon start" => Some(Self::DaemonStart),
            "daemon stop" => Some(Self::DaemonStop),
            "daemon status" => Some(Self::DaemonStatus),
            "daemon install" => Some(Self::DaemonInstall),
            "daemon restart" => Some(Self::DaemonRestart),
            "daemon uninstall" => Some(Self::DaemonUninstall),
            "diagnostics collect" => Some(Self::DiagnosticsCollect),
            "connect" => Some(Self::Connect),
            "handoff" => Some(Self::Handoff),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WireVersionCommandOutput {
    pub contract_version: u16,
    pub command: String,
    pub version: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WireHelpCommandOutput {
    pub contract_version: u16,
    pub command: String,
    pub commands: Vec<CommandName>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WireContractCommandOutput {
    pub contract_version: u16,
    pub command: String,
    pub schema_hash: String,
}
