// Generated by Bowline wire-contract generator 1.2.0. Do not edit.
// Schema SHA-256: b0b53cff526d947c34b317e79cc82aca032bb60295359f46ca9a57d7e45714a5

use super::generated::{OpaqueJson, WireStatusCommandOutput};
use serde::{Deserialize, Deserializer, Serialize, Serializer};
use std::fmt;

pub const KNOWN_DAEMON_RPC_ERROR_CODES: &[&str] = &[
    "invalid_request",
    "unsupported_version",
    "method_not_found",
    "malformed_frame",
    "frame_too_large",
    "deadline_exceeded",
    "cancelled",
    "overloaded",
    "resource_exhausted",
    "conflict",
    "not_found",
    "unavailable",
    "permission_denied",
    "internal",
];

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum DaemonRpcErrorCode {
    InvalidRequest,
    UnsupportedVersion,
    MethodNotFound,
    MalformedFrame,
    FrameTooLarge,
    DeadlineExceeded,
    Cancelled,
    Overloaded,
    ResourceExhausted,
    Conflict,
    NotFound,
    Unavailable,
    PermissionDenied,
    Internal,
    Unknown(String),
}

impl DaemonRpcErrorCode {
    pub fn as_str(&self) -> &str {
        match self {
            Self::InvalidRequest => "invalid_request",
            Self::UnsupportedVersion => "unsupported_version",
            Self::MethodNotFound => "method_not_found",
            Self::MalformedFrame => "malformed_frame",
            Self::FrameTooLarge => "frame_too_large",
            Self::DeadlineExceeded => "deadline_exceeded",
            Self::Cancelled => "cancelled",
            Self::Overloaded => "overloaded",
            Self::ResourceExhausted => "resource_exhausted",
            Self::Conflict => "conflict",
            Self::NotFound => "not_found",
            Self::Unavailable => "unavailable",
            Self::PermissionDenied => "permission_denied",
            Self::Internal => "internal",
            Self::Unknown(raw) => raw,
        }
    }
}

impl fmt::Display for DaemonRpcErrorCode {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

impl Serialize for DaemonRpcErrorCode {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for DaemonRpcErrorCode {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let raw = String::deserialize(deserializer)?;
        Ok(match raw.as_str() {
            "invalid_request" => Self::InvalidRequest,
            "unsupported_version" => Self::UnsupportedVersion,
            "method_not_found" => Self::MethodNotFound,
            "malformed_frame" => Self::MalformedFrame,
            "frame_too_large" => Self::FrameTooLarge,
            "deadline_exceeded" => Self::DeadlineExceeded,
            "cancelled" => Self::Cancelled,
            "overloaded" => Self::Overloaded,
            "resource_exhausted" => Self::ResourceExhausted,
            "conflict" => Self::Conflict,
            "not_found" => Self::NotFound,
            "unavailable" => Self::Unavailable,
            "permission_denied" => Self::PermissionDenied,
            "internal" => Self::Internal,
            _ => Self::Unknown(raw),
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DaemonClientHello {
    pub protocol: String,
    pub protocol_version: u16,
    pub contract_version: u16,
    pub schema_hash: String,
    pub client_kind: String,
    pub client_version: String,
    pub capabilities: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DaemonServerHello {
    pub protocol_version: u16,
    pub contract_version: u16,
    pub schema_hash: String,
    pub daemon_version: String,
    pub capabilities: Vec<String>,
    pub instance_id: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DaemonRpcError {
    pub code: DaemonRpcErrorCode,
    pub message: String,
    pub retryable: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub retry_after_ms: Option<u32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub operation_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub required_client_version: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub details: Option<OpaqueJson>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonRpcRequest {
    pub request_id: String,
    pub method: String,
    pub params: OpaqueJson,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deadline_ms: Option<u32>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonRpcResponse {
    pub request_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub result: Option<OpaqueJson>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<DaemonRpcError>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonRpcEvent {
    pub subscription_id: String,
    pub sequence: u64,
    pub event_kind: String,
    pub payload: OpaqueJson,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonRpcCancel {
    pub request_id: String,
}

pub const KNOWN_DAEMON_SYNC_BARRIER_OBSERVER_STATES: &[&str] = &["live"];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum DaemonSyncBarrierObserverState {
    #[serde(rename = "live")]
    Live,
}

impl DaemonSyncBarrierObserverState {
    pub const ALL: &'static [Self] = &[Self::Live];

    pub const fn token(self) -> &'static str {
        match self {
            Self::Live => "live",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "live" => Some(Self::Live),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonSyncBarrierRefIdentity {
    pub version: u64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub manifest_key: Option<String>,
}

pub const KNOWN_DAEMON_SYNC_BARRIER_RECOVERY_LIFECYCLES: &[&str] = &["nominal"];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum DaemonSyncBarrierRecoveryLifecycle {
    #[serde(rename = "nominal")]
    Nominal,
}

impl DaemonSyncBarrierRecoveryLifecycle {
    pub const ALL: &'static [Self] = &[Self::Nominal];

    pub const fn token(self) -> &'static str {
        match self {
            Self::Nominal => "nominal",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "nominal" => Some(Self::Nominal),
            _ => None,
        }
    }
}

pub const KNOWN_DAEMON_SYNC_BARRIER_WORKSPACE_STATES: &[&str] = &["ready"];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum DaemonSyncBarrierWorkspaceState {
    #[serde(rename = "ready")]
    Ready,
}

impl DaemonSyncBarrierWorkspaceState {
    pub const ALL: &'static [Self] = &[Self::Ready];

    pub const fn token(self) -> &'static str {
        match self {
            Self::Ready => "ready",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "ready" => Some(Self::Ready),
            _ => None,
        }
    }
}

pub const KNOWN_DAEMON_SYNC_BARRIER_NATIVE_LOSSS: &[&str] = &[
    "user_dropped",
    "kernel_dropped",
    "event_ids_wrapped",
    "root_changed",
    "stream_stopped",
    "non_monotonic_cursor",
    "queue_overflow",
    "backend_failure",
];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum DaemonSyncBarrierNativeLoss {
    #[serde(rename = "user_dropped")]
    UserDropped,
    #[serde(rename = "kernel_dropped")]
    KernelDropped,
    #[serde(rename = "event_ids_wrapped")]
    EventIdsWrapped,
    #[serde(rename = "root_changed")]
    RootChanged,
    #[serde(rename = "stream_stopped")]
    StreamStopped,
    #[serde(rename = "non_monotonic_cursor")]
    NonMonotonicCursor,
    #[serde(rename = "queue_overflow")]
    QueueOverflow,
    #[serde(rename = "backend_failure")]
    BackendFailure,
}

impl DaemonSyncBarrierNativeLoss {
    pub const ALL: &'static [Self] = &[
        Self::UserDropped,
        Self::KernelDropped,
        Self::EventIdsWrapped,
        Self::RootChanged,
        Self::StreamStopped,
        Self::NonMonotonicCursor,
        Self::QueueOverflow,
        Self::BackendFailure,
    ];

    pub const fn token(self) -> &'static str {
        match self {
            Self::UserDropped => "user_dropped",
            Self::KernelDropped => "kernel_dropped",
            Self::EventIdsWrapped => "event_ids_wrapped",
            Self::RootChanged => "root_changed",
            Self::StreamStopped => "stream_stopped",
            Self::NonMonotonicCursor => "non_monotonic_cursor",
            Self::QueueOverflow => "queue_overflow",
            Self::BackendFailure => "backend_failure",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "user_dropped" => Some(Self::UserDropped),
            "kernel_dropped" => Some(Self::KernelDropped),
            "event_ids_wrapped" => Some(Self::EventIdsWrapped),
            "root_changed" => Some(Self::RootChanged),
            "stream_stopped" => Some(Self::StreamStopped),
            "non_monotonic_cursor" => Some(Self::NonMonotonicCursor),
            "queue_overflow" => Some(Self::QueueOverflow),
            "backend_failure" => Some(Self::BackendFailure),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonSyncBarrierProcessIdentity {
    pub boot_id: String,
    pub session_id: String,
    pub started_at: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonSyncBarrierConvergenceSource {
    pub process_identity: DaemonSyncBarrierProcessIdentity,
    pub workspace_identity: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonSyncBarrierEngineConvergence {
    pub source: DaemonSyncBarrierConvergenceSource,
    pub barrier_id: String,
    pub endpoint_generation: u64,
    pub engine_revision: u64,
    pub materialization_revision: u64,
    pub admitted_at: String,
    pub completed_at: String,
    pub observed_ref: DaemonSyncBarrierRefIdentity,
    pub applied_ref: DaemonSyncBarrierRefIdentity,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonSyncBarrierObserverLiveness {
    pub state: DaemonSyncBarrierObserverState,
    pub endpoint_generation: u64,
    pub lifecycle_revision: u64,
    pub observed_at: String,
    pub observed_ref: DaemonSyncBarrierRefIdentity,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonSyncBarrierObserverConvergence {
    pub source: DaemonSyncBarrierConvergenceSource,
    pub admission: DaemonSyncBarrierObserverLiveness,
    pub completion: DaemonSyncBarrierObserverLiveness,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonSyncBarrierDarwinCursorReplay {
    pub covered_last_safe: u64,
    pub replay_from: u64,
    pub recovery_cause: Option<DaemonSyncBarrierNativeLoss>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonSyncBarrierDarwinFreshStream {
    pub fresh_from: u64,
    pub discontinuity: DaemonSyncBarrierNativeLoss,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind")]
pub enum DaemonSyncBarrierDarwinCoverageStart {
    #[serde(rename = "cursor-replay")]
    CursorReplay(Box<DaemonSyncBarrierDarwinCursorReplay>),
    #[serde(rename = "fresh-stream")]
    FreshStream(Box<DaemonSyncBarrierDarwinFreshStream>),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonSyncBarrierDarwinCoverage {
    pub boundary_id: u64,
    pub covered_epoch: u64,
    pub live_epoch: u64,
    pub coverage_start: DaemonSyncBarrierDarwinCoverageStart,
    pub history_through: u64,
    pub history_done: bool,
    pub must_scan_subdirs: bool,
    pub sealed_through: u64,
    pub flush_generation: u64,
    pub loss_generation: u64,
    pub callback_generation: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonSyncBarrierLinuxCoverage {
    pub boundary_id: u64,
    pub stream_epoch: u64,
    pub watcher_ready_control_id: u64,
    pub callback_drain_control_id: u64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind")]
pub enum DaemonSyncBarrierNativeCoverage {
    #[serde(rename = "fsevents-post-scan-seal")]
    FseventsPostScanSeal(Box<DaemonSyncBarrierDarwinCoverage>),
    #[serde(rename = "inotify-live-drain")]
    InotifyLiveDrain(Box<DaemonSyncBarrierLinuxCoverage>),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonSyncBarrierRecoveryClosure {
    pub process_identity: DaemonSyncBarrierProcessIdentity,
    pub incident_id: String,
    pub closing_attempt_id: String,
    pub attempt_count: u64,
    pub scan_count: u64,
    pub captured_activity_watermark: u64,
    pub final_activity_watermark: u64,
    pub authoritative_scan_revision: u64,
    pub native_boundary: DaemonSyncBarrierNativeCoverage,
    pub closing_recovery_revision: u64,
    pub closed_at: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonSyncBarrierCoordinatorFrontier {
    pub lifecycle: DaemonSyncBarrierRecoveryLifecycle,
    pub recovery_snapshot_revision: u64,
    pub closing_recovery_revision: u64,
    pub activity_watermark: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonSyncBarrierWorkspaceStatus {
    pub state: DaemonSyncBarrierWorkspaceState,
    pub observed_at: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonSyncBarrierResult {
    pub barrier_id: String,
    pub process_identity: DaemonSyncBarrierProcessIdentity,
    pub workspace_identity: String,
    pub engine_convergence: DaemonSyncBarrierEngineConvergence,
    pub observer: DaemonSyncBarrierObserverConvergence,
    pub coordinator_nominal_frontier: DaemonSyncBarrierCoordinatorFrontier,
    pub recovery_closure: Option<DaemonSyncBarrierRecoveryClosure>,
    pub workspace_status: DaemonSyncBarrierWorkspaceStatus,
    pub linearized_at: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonStatusScopeParams {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub workspace_root: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub project_path: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requested_path: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonStatusSnapshotResult {
    pub instance_id: String,
    pub sequence: u64,
    pub snapshot: WireStatusCommandOutput,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonStatusSubscribeResult {
    pub subscription_id: String,
    pub instance_id: String,
    pub sequence: u64,
    pub snapshot: WireStatusCommandOutput,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonStatusEventPayload {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub snapshot: Option<WireStatusCommandOutput>,
    pub gap: bool,
    pub resync_required: bool,
    pub heartbeat: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonDeviceActionParams {
    pub request_id: String,
    pub idempotency_key: String,
}

pub const KNOWN_DAEMON_SYNC_RESOURCE_KINDS: &[&str] =
    &["workspace-sync", "conflict-followup", "post-commit"];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum DaemonSyncResourceKind {
    #[serde(rename = "workspace-sync")]
    WorkspaceSync,
    #[serde(rename = "conflict-followup")]
    ConflictFollowup,
    #[serde(rename = "post-commit")]
    PostCommit,
}

impl DaemonSyncResourceKind {
    pub const ALL: &'static [Self] = &[
        Self::WorkspaceSync,
        Self::ConflictFollowup,
        Self::PostCommit,
    ];

    pub const fn token(self) -> &'static str {
        match self {
            Self::WorkspaceSync => "workspace-sync",
            Self::ConflictFollowup => "conflict-followup",
            Self::PostCommit => "post-commit",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "workspace-sync" => Some(Self::WorkspaceSync),
            "conflict-followup" => Some(Self::ConflictFollowup),
            "post-commit" => Some(Self::PostCommit),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonSyncResource {
    pub kind: DaemonSyncResourceKind,
    pub workspace_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conflict_id: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DaemonCancelOperationParams {
    pub operation_id: String,
}
