// Generated by Bowline wire-contract generator 1.2.0. Do not edit.
// Schema SHA-256: 90aaff183a675d00a355085f8a588d3d135b786f9e88fb8cde5c8a153078173e

use super::generated::EventName;
use serde::{Deserialize, Serialize};

pub const KNOWN_WIRE_STATUS_LEVELS: &[&str] = &["healthy", "attention", "limited"];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum WireStatusLevel {
    #[serde(rename = "healthy")]
    Healthy,
    #[serde(rename = "attention")]
    Attention,
    #[serde(rename = "limited")]
    Limited,
}

impl WireStatusLevel {
    pub const ALL: &'static [Self] = &[Self::Healthy, Self::Attention, Self::Limited];

    pub const fn token(self) -> &'static str {
        match self {
            Self::Healthy => "healthy",
            Self::Attention => "attention",
            Self::Limited => "limited",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "healthy" => Some(Self::Healthy),
            "attention" => Some(Self::Attention),
            "limited" => Some(Self::Limited),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeviceApprovalAffordance {
    pub request_id: String,
    pub device_name: String,
    pub code: String,
    pub approve_command: String,
}

pub const KNOWN_WIRE_STATUS_SCOPES: &[&str] = &["project", "workspace", "lease"];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum WireStatusScope {
    #[serde(rename = "project")]
    Project,
    #[serde(rename = "workspace")]
    Workspace,
    #[serde(rename = "lease")]
    Lease,
}

impl WireStatusScope {
    pub const ALL: &'static [Self] = &[Self::Project, Self::Workspace, Self::Lease];

    pub const fn token(self) -> &'static str {
        match self {
            Self::Project => "project",
            Self::Workspace => "workspace",
            Self::Lease => "lease",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "project" => Some(Self::Project),
            "workspace" => Some(Self::Workspace),
            "lease" => Some(Self::Lease),
            _ => None,
        }
    }
}

pub const KNOWN_WIRE_STATUS_ITEM_KINDS: &[&str] = &[
    "continuity",
    "policy",
    "device",
    "conflict",
    "work-view",
    "lease",
    "watcher",
    "env",
    "source",
    "setup",
    "metadata",
    "materialization",
    "network",
    "update",
];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum WireStatusItemKind {
    #[serde(rename = "continuity")]
    Continuity,
    #[serde(rename = "policy")]
    Policy,
    #[serde(rename = "device")]
    Device,
    #[serde(rename = "conflict")]
    Conflict,
    #[serde(rename = "work-view")]
    WorkView,
    #[serde(rename = "lease")]
    Lease,
    #[serde(rename = "watcher")]
    Watcher,
    #[serde(rename = "env")]
    Env,
    #[serde(rename = "source")]
    Source,
    #[serde(rename = "setup")]
    Setup,
    #[serde(rename = "metadata")]
    Metadata,
    #[serde(rename = "materialization")]
    Materialization,
    #[serde(rename = "network")]
    Network,
    #[serde(rename = "update")]
    Update,
}

impl WireStatusItemKind {
    pub const ALL: &'static [Self] = &[
        Self::Continuity,
        Self::Policy,
        Self::Device,
        Self::Conflict,
        Self::WorkView,
        Self::Lease,
        Self::Watcher,
        Self::Env,
        Self::Source,
        Self::Setup,
        Self::Metadata,
        Self::Materialization,
        Self::Network,
        Self::Update,
    ];

    pub const fn token(self) -> &'static str {
        match self {
            Self::Continuity => "continuity",
            Self::Policy => "policy",
            Self::Device => "device",
            Self::Conflict => "conflict",
            Self::WorkView => "work-view",
            Self::Lease => "lease",
            Self::Watcher => "watcher",
            Self::Env => "env",
            Self::Source => "source",
            Self::Setup => "setup",
            Self::Metadata => "metadata",
            Self::Materialization => "materialization",
            Self::Network => "network",
            Self::Update => "update",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "continuity" => Some(Self::Continuity),
            "policy" => Some(Self::Policy),
            "device" => Some(Self::Device),
            "conflict" => Some(Self::Conflict),
            "work-view" => Some(Self::WorkView),
            "lease" => Some(Self::Lease),
            "watcher" => Some(Self::Watcher),
            "env" => Some(Self::Env),
            "source" => Some(Self::Source),
            "setup" => Some(Self::Setup),
            "metadata" => Some(Self::Metadata),
            "materialization" => Some(Self::Materialization),
            "network" => Some(Self::Network),
            "update" => Some(Self::Update),
            _ => None,
        }
    }
}

pub const KNOWN_WIRE_STATUS_SUBJECT_KINDS: &[&str] = &[
    "workspace",
    "root",
    "project",
    "path",
    "snapshot",
    "env-record",
    "policy",
    "setup-receipt",
    "conflict",
    "work-view",
    "lease",
    "overlay",
    "device",
    "device-approval-request",
    "metadata",
    "component",
];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum WireStatusSubjectKind {
    #[serde(rename = "workspace")]
    Workspace,
    #[serde(rename = "root")]
    Root,
    #[serde(rename = "project")]
    Project,
    #[serde(rename = "path")]
    Path,
    #[serde(rename = "snapshot")]
    Snapshot,
    #[serde(rename = "env-record")]
    EnvRecord,
    #[serde(rename = "policy")]
    Policy,
    #[serde(rename = "setup-receipt")]
    SetupReceipt,
    #[serde(rename = "conflict")]
    Conflict,
    #[serde(rename = "work-view")]
    WorkView,
    #[serde(rename = "lease")]
    Lease,
    #[serde(rename = "overlay")]
    Overlay,
    #[serde(rename = "device")]
    Device,
    #[serde(rename = "device-approval-request")]
    DeviceApprovalRequest,
    #[serde(rename = "metadata")]
    Metadata,
    #[serde(rename = "component")]
    Component,
}

impl WireStatusSubjectKind {
    pub const ALL: &'static [Self] = &[
        Self::Workspace,
        Self::Root,
        Self::Project,
        Self::Path,
        Self::Snapshot,
        Self::EnvRecord,
        Self::Policy,
        Self::SetupReceipt,
        Self::Conflict,
        Self::WorkView,
        Self::Lease,
        Self::Overlay,
        Self::Device,
        Self::DeviceApprovalRequest,
        Self::Metadata,
        Self::Component,
    ];

    pub const fn token(self) -> &'static str {
        match self {
            Self::Workspace => "workspace",
            Self::Root => "root",
            Self::Project => "project",
            Self::Path => "path",
            Self::Snapshot => "snapshot",
            Self::EnvRecord => "env-record",
            Self::Policy => "policy",
            Self::SetupReceipt => "setup-receipt",
            Self::Conflict => "conflict",
            Self::WorkView => "work-view",
            Self::Lease => "lease",
            Self::Overlay => "overlay",
            Self::Device => "device",
            Self::DeviceApprovalRequest => "device-approval-request",
            Self::Metadata => "metadata",
            Self::Component => "component",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "workspace" => Some(Self::Workspace),
            "root" => Some(Self::Root),
            "project" => Some(Self::Project),
            "path" => Some(Self::Path),
            "snapshot" => Some(Self::Snapshot),
            "env-record" => Some(Self::EnvRecord),
            "policy" => Some(Self::Policy),
            "setup-receipt" => Some(Self::SetupReceipt),
            "conflict" => Some(Self::Conflict),
            "work-view" => Some(Self::WorkView),
            "lease" => Some(Self::Lease),
            "overlay" => Some(Self::Overlay),
            "device" => Some(Self::Device),
            "device-approval-request" => Some(Self::DeviceApprovalRequest),
            "metadata" => Some(Self::Metadata),
            "component" => Some(Self::Component),
            _ => None,
        }
    }
}

pub const KNOWN_WIRE_PATH_CLASSIFICATIONS: &[&str] = &[
    "workspace-sync",
    "project-env",
    "generated",
    "dependency",
    "cache",
    "large-file",
    "secret-looking",
    "local-only",
    "blocked",
];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum WirePathClassification {
    #[serde(rename = "workspace-sync")]
    WorkspaceSync,
    #[serde(rename = "project-env")]
    ProjectEnv,
    #[serde(rename = "generated")]
    Generated,
    #[serde(rename = "dependency")]
    Dependency,
    #[serde(rename = "cache")]
    Cache,
    #[serde(rename = "large-file")]
    LargeFile,
    #[serde(rename = "secret-looking")]
    SecretLooking,
    #[serde(rename = "local-only")]
    LocalOnly,
    #[serde(rename = "blocked")]
    Blocked,
}

impl WirePathClassification {
    pub const ALL: &'static [Self] = &[
        Self::WorkspaceSync,
        Self::ProjectEnv,
        Self::Generated,
        Self::Dependency,
        Self::Cache,
        Self::LargeFile,
        Self::SecretLooking,
        Self::LocalOnly,
        Self::Blocked,
    ];

    pub const fn token(self) -> &'static str {
        match self {
            Self::WorkspaceSync => "workspace-sync",
            Self::ProjectEnv => "project-env",
            Self::Generated => "generated",
            Self::Dependency => "dependency",
            Self::Cache => "cache",
            Self::LargeFile => "large-file",
            Self::SecretLooking => "secret-looking",
            Self::LocalOnly => "local-only",
            Self::Blocked => "blocked",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "workspace-sync" => Some(Self::WorkspaceSync),
            "project-env" => Some(Self::ProjectEnv),
            "generated" => Some(Self::Generated),
            "dependency" => Some(Self::Dependency),
            "cache" => Some(Self::Cache),
            "large-file" => Some(Self::LargeFile),
            "secret-looking" => Some(Self::SecretLooking),
            "local-only" => Some(Self::LocalOnly),
            "blocked" => Some(Self::Blocked),
            _ => None,
        }
    }
}

pub const KNOWN_WIRE_MATERIALIZATION_MODES: &[&str] = &[
    "workspace-sync",
    "project-env",
    "encrypted-sync",
    "lazy",
    "structure-only",
    "local-regenerate",
    "local-cache",
    "ignore",
    "local-only",
    "blocked",
];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum WireMaterializationMode {
    #[serde(rename = "workspace-sync")]
    WorkspaceSync,
    #[serde(rename = "project-env")]
    ProjectEnv,
    #[serde(rename = "encrypted-sync")]
    EncryptedSync,
    #[serde(rename = "lazy")]
    Lazy,
    #[serde(rename = "structure-only")]
    StructureOnly,
    #[serde(rename = "local-regenerate")]
    LocalRegenerate,
    #[serde(rename = "local-cache")]
    LocalCache,
    #[serde(rename = "ignore")]
    Ignore,
    #[serde(rename = "local-only")]
    LocalOnly,
    #[serde(rename = "blocked")]
    Blocked,
}

impl WireMaterializationMode {
    pub const ALL: &'static [Self] = &[
        Self::WorkspaceSync,
        Self::ProjectEnv,
        Self::EncryptedSync,
        Self::Lazy,
        Self::StructureOnly,
        Self::LocalRegenerate,
        Self::LocalCache,
        Self::Ignore,
        Self::LocalOnly,
        Self::Blocked,
    ];

    pub const fn token(self) -> &'static str {
        match self {
            Self::WorkspaceSync => "workspace-sync",
            Self::ProjectEnv => "project-env",
            Self::EncryptedSync => "encrypted-sync",
            Self::Lazy => "lazy",
            Self::StructureOnly => "structure-only",
            Self::LocalRegenerate => "local-regenerate",
            Self::LocalCache => "local-cache",
            Self::Ignore => "ignore",
            Self::LocalOnly => "local-only",
            Self::Blocked => "blocked",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "workspace-sync" => Some(Self::WorkspaceSync),
            "project-env" => Some(Self::ProjectEnv),
            "encrypted-sync" => Some(Self::EncryptedSync),
            "lazy" => Some(Self::Lazy),
            "structure-only" => Some(Self::StructureOnly),
            "local-regenerate" => Some(Self::LocalRegenerate),
            "local-cache" => Some(Self::LocalCache),
            "ignore" => Some(Self::Ignore),
            "local-only" => Some(Self::LocalOnly),
            "blocked" => Some(Self::Blocked),
            _ => None,
        }
    }
}

pub const KNOWN_WIRE_ACCESS_FLAGS: &[&str] = &[
    "human-readable",
    "agent-readable",
    "agent-hidden",
    "lease-only",
];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum WireAccessFlag {
    #[serde(rename = "human-readable")]
    HumanReadable,
    #[serde(rename = "agent-readable")]
    AgentReadable,
    #[serde(rename = "agent-hidden")]
    AgentHidden,
    #[serde(rename = "lease-only")]
    LeaseOnly,
}

impl WireAccessFlag {
    pub const ALL: &'static [Self] = &[
        Self::HumanReadable,
        Self::AgentReadable,
        Self::AgentHidden,
        Self::LeaseOnly,
    ];

    pub const fn token(self) -> &'static str {
        match self {
            Self::HumanReadable => "human-readable",
            Self::AgentReadable => "agent-readable",
            Self::AgentHidden => "agent-hidden",
            Self::LeaseOnly => "lease-only",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "human-readable" => Some(Self::HumanReadable),
            "agent-readable" => Some(Self::AgentReadable),
            "agent-hidden" => Some(Self::AgentHidden),
            "lease-only" => Some(Self::LeaseOnly),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WireStatusSubject {
    pub kind: WireStatusSubjectKind,
    pub id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WireWorkspaceStatus {
    pub level: WireStatusLevel,
    pub attention_items: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WireStatusItem {
    pub kind: WireStatusItemKind,
    pub summary: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subject: Option<WireStatusSubject>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub classification: Option<WirePathClassification>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mode: Option<WireMaterializationMode>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub access: Option<Vec<WireAccessFlag>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub event_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub event_name: Option<EventName>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub device_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lease_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub snapshot_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub policy_version: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub env_record_id: Option<String>,
}

pub const KNOWN_WIRE_COMPONENT_STATES: &[&str] = &["ready", "degraded", "unavailable"];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum WireComponentState {
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "degraded")]
    Degraded,
    #[serde(rename = "unavailable")]
    Unavailable,
}

impl WireComponentState {
    pub const ALL: &'static [Self] = &[Self::Ready, Self::Degraded, Self::Unavailable];

    pub const fn token(self) -> &'static str {
        match self {
            Self::Ready => "ready",
            Self::Degraded => "degraded",
            Self::Unavailable => "unavailable",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "ready" => Some(Self::Ready),
            "degraded" => Some(Self::Degraded),
            "unavailable" => Some(Self::Unavailable),
            _ => None,
        }
    }
}

pub const KNOWN_WIRE_NETWORK_STATES: &[&str] = &["online", "degraded", "offline"];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum WireNetworkState {
    #[serde(rename = "online")]
    Online,
    #[serde(rename = "degraded")]
    Degraded,
    #[serde(rename = "offline")]
    Offline,
}

impl WireNetworkState {
    pub const ALL: &'static [Self] = &[Self::Online, Self::Degraded, Self::Offline];

    pub const fn token(self) -> &'static str {
        match self {
            Self::Online => "online",
            Self::Degraded => "degraded",
            Self::Offline => "offline",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "online" => Some(Self::Online),
            "degraded" => Some(Self::Degraded),
            "offline" => Some(Self::Offline),
            _ => None,
        }
    }
}

pub const KNOWN_WIRE_FRESHNESS_AXISS: &[&str] = &["snapshot", "git"];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum WireFreshnessAxis {
    #[serde(rename = "snapshot")]
    Snapshot,
    #[serde(rename = "git")]
    Git,
}

impl WireFreshnessAxis {
    pub const ALL: &'static [Self] = &[Self::Snapshot, Self::Git];

    pub const fn token(self) -> &'static str {
        match self {
            Self::Snapshot => "snapshot",
            Self::Git => "git",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "snapshot" => Some(Self::Snapshot),
            "git" => Some(Self::Git),
            _ => None,
        }
    }
}

pub const KNOWN_WIRE_FRESHNESS_VERDICTS: &[&str] = &["current", "behind", "diverged", "unknown"];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum WireFreshnessVerdict {
    #[serde(rename = "current")]
    Current,
    #[serde(rename = "behind")]
    Behind,
    #[serde(rename = "diverged")]
    Diverged,
    #[serde(rename = "unknown")]
    Unknown,
}

impl WireFreshnessVerdict {
    pub const ALL: &'static [Self] = &[Self::Current, Self::Behind, Self::Diverged, Self::Unknown];

    pub const fn token(self) -> &'static str {
        match self {
            Self::Current => "current",
            Self::Behind => "behind",
            Self::Diverged => "diverged",
            Self::Unknown => "unknown",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "current" => Some(Self::Current),
            "behind" => Some(Self::Behind),
            "diverged" => Some(Self::Diverged),
            "unknown" => Some(Self::Unknown),
            _ => None,
        }
    }
}

pub const KNOWN_WIRE_PROJECT_SETUP_READINESS_STATES: &[&str] =
    &["unknown", "runnable", "needs-setup", "blocked"];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum WireProjectSetupReadinessState {
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "runnable")]
    Runnable,
    #[serde(rename = "needs-setup")]
    NeedsSetup,
    #[serde(rename = "blocked")]
    Blocked,
}

impl WireProjectSetupReadinessState {
    pub const ALL: &'static [Self] = &[
        Self::Unknown,
        Self::Runnable,
        Self::NeedsSetup,
        Self::Blocked,
    ];

    pub const fn token(self) -> &'static str {
        match self {
            Self::Unknown => "unknown",
            Self::Runnable => "runnable",
            Self::NeedsSetup => "needs-setup",
            Self::Blocked => "blocked",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "unknown" => Some(Self::Unknown),
            "runnable" => Some(Self::Runnable),
            "needs-setup" => Some(Self::NeedsSetup),
            "blocked" => Some(Self::Blocked),
            _ => None,
        }
    }
}

pub const KNOWN_WIRE_SETUP_RECEIPT_STATES: &[&str] =
    &["approved", "approval-required", "completed", "failed"];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum WireSetupReceiptState {
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "approval-required")]
    ApprovalRequired,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
}

impl WireSetupReceiptState {
    pub const ALL: &'static [Self] = &[
        Self::Approved,
        Self::ApprovalRequired,
        Self::Completed,
        Self::Failed,
    ];

    pub const fn token(self) -> &'static str {
        match self {
            Self::Approved => "approved",
            Self::ApprovalRequired => "approval-required",
            Self::Completed => "completed",
            Self::Failed => "failed",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "approved" => Some(Self::Approved),
            "approval-required" => Some(Self::ApprovalRequired),
            "completed" => Some(Self::Completed),
            "failed" => Some(Self::Failed),
            _ => None,
        }
    }
}

pub const KNOWN_WIRE_CONTROL_PLANE_SUPPORT_CAPABILITIES: &[&str] = &[
    "device-approval",
    "project-scoped-workspace-ref-cas",
    "work-view",
    "agent-lease",
    "encrypted-object-store",
    "recovery",
];

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum WireControlPlaneSupportCapability {
    #[serde(rename = "device-approval")]
    DeviceApproval,
    #[serde(rename = "project-scoped-workspace-ref-cas")]
    ProjectScopedWorkspaceRefCas,
    #[serde(rename = "work-view")]
    WorkView,
    #[serde(rename = "agent-lease")]
    AgentLease,
    #[serde(rename = "encrypted-object-store")]
    EncryptedObjectStore,
    #[serde(rename = "recovery")]
    Recovery,
}

impl WireControlPlaneSupportCapability {
    pub const ALL: &'static [Self] = &[
        Self::DeviceApproval,
        Self::ProjectScopedWorkspaceRefCas,
        Self::WorkView,
        Self::AgentLease,
        Self::EncryptedObjectStore,
        Self::Recovery,
    ];

    pub const fn token(self) -> &'static str {
        match self {
            Self::DeviceApproval => "device-approval",
            Self::ProjectScopedWorkspaceRefCas => "project-scoped-workspace-ref-cas",
            Self::WorkView => "work-view",
            Self::AgentLease => "agent-lease",
            Self::EncryptedObjectStore => "encrypted-object-store",
            Self::Recovery => "recovery",
        }
    }

    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "device-approval" => Some(Self::DeviceApproval),
            "project-scoped-workspace-ref-cas" => Some(Self::ProjectScopedWorkspaceRefCas),
            "work-view" => Some(Self::WorkView),
            "agent-lease" => Some(Self::AgentLease),
            "encrypted-object-store" => Some(Self::EncryptedObjectStore),
            "recovery" => Some(Self::Recovery),
            _ => None,
        }
    }
}
