export const COMMAND_NAMES = [
  "help",
  "version",
  "contract",
  "mcp",
  "update",
  "unknown",
  "login",
  "logout",
  "device approve",
  "device deny",
  "device revoke",
  "recover",
  "setup",
  "status",
  "device list",
  "device request",
  "device accept",
  "events",
  "history",
  "tui",
  "resolve",
  "work create",
  "work list",
  "work diff",
  "work review",
  "work accept",
  "work discard",
  "work restore",
  "work cleanup",
  "forget-local",
  "archive",
  "purge",
  "agent start",
  "agent context",
  "agent prompt",
  "agent complete",
  "agent cancel",
  "agent extend",
  "agent mcp-token",
  "lease join",
  "daemon start",
  "daemon stop",
  "daemon status",
  "daemon install",
  "daemon restart",
  "daemon uninstall",
  "diagnostics collect",
  "connect",
  "handoff",
] as const;
export type CommandName = (typeof COMMAND_NAMES)[number];
