export const COMMAND_NAMES = [
  "help",
  "version",
  "contract",
  "update",
  "unknown",
  "login",
  "logout",
  "device approve",
  "device deny",
  "device revoke",
  "recover",
  "setup",
  "status",
  "device list",
  "device request",
  "device accept",
  "events",
  "tui",
  "work create",
  "work list",
  "work diff",
  "work review",
  "work accept",
  "work discard",
  "work restore",
  "work cleanup",
  "forget-local",
  "archive",
  "purge",
  "daemon start",
  "daemon stop",
  "daemon status",
  "daemon install",
  "daemon restart",
  "daemon uninstall",
  "diagnostics collect",
  "doctor",
  "connect",
] as const;
export type CommandName = (typeof COMMAND_NAMES)[number];
