// Generated by Bowline wire-contract generator 1.2.0. Do not edit.
// Schema SHA-256: 4ba7588109ebc1681e45961ce7cfc67a1cfb121e39447807957b0f64adb3ab98

#[path = "generated/hosted_refs_list_workspace_ref_history_request.rs"]
mod hosted_refs_list_workspace_ref_history_request;
pub(in crate::hosted) use hosted_refs_list_workspace_ref_history_request::*;

#[path = "generated/hosted_workspace_ref_history_record.rs"]
mod hosted_workspace_ref_history_record;
pub(in crate::hosted) use hosted_workspace_ref_history_record::*;

#[path = "generated/hosted_refs_list_workspace_ref_history_response.rs"]
mod hosted_refs_list_workspace_ref_history_response;
pub(in crate::hosted) use hosted_refs_list_workspace_ref_history_response::*;

#[path = "generated/hosted_retention_state.rs"]
mod hosted_retention_state;
pub(in crate::hosted) use hosted_retention_state::*;

#[path = "generated/hosted_gc_delete_skip_reason.rs"]
mod hosted_gc_delete_skip_reason;
pub(in crate::hosted) use hosted_gc_delete_skip_reason::*;

#[path = "generated/hosted_storage_gc_object_ref.rs"]
mod hosted_storage_gc_object_ref;
pub(in crate::hosted) use hosted_storage_gc_object_ref::*;

#[path = "generated/hosted_retention_list_storage_gc_objects_request.rs"]
mod hosted_retention_list_storage_gc_objects_request;
pub(in crate::hosted) use hosted_retention_list_storage_gc_objects_request::*;

#[path = "generated/hosted_retention_list_storage_gc_objects_response.rs"]
mod hosted_retention_list_storage_gc_objects_response;
pub(in crate::hosted) use hosted_retention_list_storage_gc_objects_response::*;

#[path = "generated/hosted_retention_delete_object_metadata_after_gc_request.rs"]
mod hosted_retention_delete_object_metadata_after_gc_request;
pub(in crate::hosted) use hosted_retention_delete_object_metadata_after_gc_request::*;

#[path = "generated/hosted_retention_delete_object_metadata_after_gc_response.rs"]
mod hosted_retention_delete_object_metadata_after_gc_response;
pub(in crate::hosted) use hosted_retention_delete_object_metadata_after_gc_response::*;

#[path = "generated/hosted_recovery_envelope_state.rs"]
mod hosted_recovery_envelope_state;
pub(in crate::hosted) use hosted_recovery_envelope_state::*;

#[path = "generated/hosted_recovery_envelope.rs"]
mod hosted_recovery_envelope;
pub(in crate::hosted) use hosted_recovery_envelope::*;

#[path = "generated/hosted_recovery_device_grant.rs"]
mod hosted_recovery_device_grant;
pub(in crate::hosted) use hosted_recovery_device_grant::*;

#[path = "generated/hosted_recovery_get_recovery_envelopes_request.rs"]
mod hosted_recovery_get_recovery_envelopes_request;
pub(in crate::hosted) use hosted_recovery_get_recovery_envelopes_request::*;

#[path = "generated/hosted_recovery_get_recovery_envelopes_response.rs"]
mod hosted_recovery_get_recovery_envelopes_response;
pub(in crate::hosted) use hosted_recovery_get_recovery_envelopes_response::*;

#[path = "generated/hosted_recovery_create_recovery_envelope_request.rs"]
mod hosted_recovery_create_recovery_envelope_request;
pub(in crate::hosted) use hosted_recovery_create_recovery_envelope_request::*;

#[path = "generated/hosted_recovery_rotate_recovery_envelope_request.rs"]
mod hosted_recovery_rotate_recovery_envelope_request;
pub(in crate::hosted) use hosted_recovery_rotate_recovery_envelope_request::*;

#[path = "generated/hosted_recovery_revoke_recovery_envelope_request.rs"]
mod hosted_recovery_revoke_recovery_envelope_request;
pub(in crate::hosted) use hosted_recovery_revoke_recovery_envelope_request::*;

#[path = "generated/hosted_recovery_verify_recovery_envelope_request.rs"]
mod hosted_recovery_verify_recovery_envelope_request;
pub(in crate::hosted) use hosted_recovery_verify_recovery_envelope_request::*;

#[path = "generated/hosted_recovery_authorize_device_with_recovery_request.rs"]
mod hosted_recovery_authorize_device_with_recovery_request;
pub(in crate::hosted) use hosted_recovery_authorize_device_with_recovery_request::*;

#[path = "generated/hosted_device_request_state.rs"]
mod hosted_device_request_state;
pub(in crate::hosted) use hosted_device_request_state::*;

#[path = "generated/hosted_device_request.rs"]
mod hosted_device_request;
pub(in crate::hosted) use hosted_device_request::*;

#[path = "generated/hosted_authorized_device.rs"]
mod hosted_authorized_device;
pub(in crate::hosted) use hosted_authorized_device::*;

#[path = "generated/hosted_revoked_device.rs"]
mod hosted_revoked_device;
pub(in crate::hosted) use hosted_revoked_device::*;

#[path = "generated/hosted_bootstrap_session.rs"]
mod hosted_bootstrap_session;
pub(in crate::hosted) use hosted_bootstrap_session::*;

#[path = "generated/hosted_device_approval.rs"]
mod hosted_device_approval;
pub(in crate::hosted) use hosted_device_approval::*;

#[path = "generated/hosted_device_denial.rs"]
mod hosted_device_denial;
pub(in crate::hosted) use hosted_device_denial::*;

#[path = "generated/hosted_device_approval_or_null.rs"]
mod hosted_device_approval_or_null;
pub(in crate::hosted) use hosted_device_approval_or_null::*;

#[path = "generated/hosted_devices_list_device_trust_response.rs"]
mod hosted_devices_list_device_trust_response;
pub(in crate::hosted) use hosted_devices_list_device_trust_response::*;

#[path = "generated/hosted_devices_approve_device_request_request.rs"]
mod hosted_devices_approve_device_request_request;
pub(in crate::hosted) use hosted_devices_approve_device_request_request::*;

#[path = "generated/hosted_devices_confirm_grant_accepted_request.rs"]
mod hosted_devices_confirm_grant_accepted_request;
pub(in crate::hosted) use hosted_devices_confirm_grant_accepted_request::*;

#[path = "generated/hosted_devices_confirm_grant_accepted_with_bootstrap_request.rs"]
mod hosted_devices_confirm_grant_accepted_with_bootstrap_request;
pub(in crate::hosted) use hosted_devices_confirm_grant_accepted_with_bootstrap_request::*;

#[path = "generated/hosted_devices_create_bootstrap_session_request.rs"]
mod hosted_devices_create_bootstrap_session_request;
pub(in crate::hosted) use hosted_devices_create_bootstrap_session_request::*;

#[path = "generated/hosted_devices_create_first_authorized_device_request.rs"]
mod hosted_devices_create_first_authorized_device_request;
pub(in crate::hosted) use hosted_devices_create_first_authorized_device_request::*;

#[path = "generated/hosted_devices_create_pending_device_request.rs"]
mod hosted_devices_create_pending_device_request;
pub(in crate::hosted) use hosted_devices_create_pending_device_request::*;

#[path = "generated/hosted_devices_create_pending_device_with_bootstrap_request.rs"]
mod hosted_devices_create_pending_device_with_bootstrap_request;
pub(in crate::hosted) use hosted_devices_create_pending_device_with_bootstrap_request::*;

#[path = "generated/hosted_devices_deny_device_request_request.rs"]
mod hosted_devices_deny_device_request_request;
pub(in crate::hosted) use hosted_devices_deny_device_request_request::*;

#[path = "generated/hosted_devices_get_encrypted_grant_request.rs"]
mod hosted_devices_get_encrypted_grant_request;
pub(in crate::hosted) use hosted_devices_get_encrypted_grant_request::*;

#[path = "generated/hosted_devices_get_encrypted_grant_with_bootstrap_request.rs"]
mod hosted_devices_get_encrypted_grant_with_bootstrap_request;
pub(in crate::hosted) use hosted_devices_get_encrypted_grant_with_bootstrap_request::*;

#[path = "generated/hosted_devices_list_device_trust_request.rs"]
mod hosted_devices_list_device_trust_request;
pub(in crate::hosted) use hosted_devices_list_device_trust_request::*;

#[path = "generated/hosted_devices_revoke_device_request.rs"]
mod hosted_devices_revoke_device_request;
pub(in crate::hosted) use hosted_devices_revoke_device_request::*;

#[path = "generated/hosted_object_kind.rs"]
mod hosted_object_kind;
pub(in crate::hosted) use hosted_object_kind::*;

#[path = "generated/hosted_object_metadata.rs"]
mod hosted_object_metadata;
pub(in crate::hosted) use hosted_object_metadata::*;

#[path = "generated/hosted_download_intent_range.rs"]
mod hosted_download_intent_range;
pub(in crate::hosted) use hosted_download_intent_range::*;

#[path = "generated/hosted_object_metadata_or_null.rs"]
mod hosted_object_metadata_or_null;
pub(in crate::hosted) use hosted_object_metadata_or_null::*;

#[path = "generated/hosted_object_pointer_input.rs"]
mod hosted_object_pointer_input;
pub(in crate::hosted) use hosted_object_pointer_input::*;

#[path = "generated/hosted_objects_create_upload_intent_request.rs"]
mod hosted_objects_create_upload_intent_request;
pub(in crate::hosted) use hosted_objects_create_upload_intent_request::*;

#[path = "generated/hosted_objects_create_download_intent_request.rs"]
mod hosted_objects_create_download_intent_request;
pub(in crate::hosted) use hosted_objects_create_download_intent_request::*;

#[path = "generated/hosted_objects_create_upload_verification_intent_request.rs"]
mod hosted_objects_create_upload_verification_intent_request;
pub(in crate::hosted) use hosted_objects_create_upload_verification_intent_request::*;

#[path = "generated/hosted_objects_mark_object_retention_state_request.rs"]
mod hosted_objects_mark_object_retention_state_request;
pub(in crate::hosted) use hosted_objects_mark_object_retention_state_request::*;

#[path = "generated/hosted_objects_create_storage_gc_delete_intent_request.rs"]
mod hosted_objects_create_storage_gc_delete_intent_request;
pub(in crate::hosted) use hosted_objects_create_storage_gc_delete_intent_request::*;

#[path = "generated/hosted_objects_commit_uploaded_object_metadata_request.rs"]
mod hosted_objects_commit_uploaded_object_metadata_request;
pub(in crate::hosted) use hosted_objects_commit_uploaded_object_metadata_request::*;

#[path = "generated/hosted_object_queries_get_object_metadata_request.rs"]
mod hosted_object_queries_get_object_metadata_request;
pub(in crate::hosted) use hosted_object_queries_get_object_metadata_request::*;

#[path = "generated/hosted_objects_create_upload_intent_response.rs"]
mod hosted_objects_create_upload_intent_response;
pub(in crate::hosted) use hosted_objects_create_upload_intent_response::*;

#[path = "generated/hosted_objects_create_download_intent_response.rs"]
mod hosted_objects_create_download_intent_response;
pub(in crate::hosted) use hosted_objects_create_download_intent_response::*;

#[path = "generated/hosted_objects_create_upload_verification_intent_response.rs"]
mod hosted_objects_create_upload_verification_intent_response;
pub(in crate::hosted) use hosted_objects_create_upload_verification_intent_response::*;

#[path = "generated/hosted_objects_create_storage_gc_delete_intent_response.rs"]
mod hosted_objects_create_storage_gc_delete_intent_response;
pub(in crate::hosted) use hosted_objects_create_storage_gc_delete_intent_response::*;

#[path = "generated/hosted_compact_event_kind.rs"]
mod hosted_compact_event_kind;
pub(in crate::hosted) use hosted_compact_event_kind::*;

#[path = "generated/hosted_status_availability.rs"]
mod hosted_status_availability;
pub(in crate::hosted) use hosted_status_availability::*;

#[path = "generated/hosted_status_attention.rs"]
mod hosted_status_attention;
pub(in crate::hosted) use hosted_status_attention::*;

#[path = "generated/hosted_status_freshness.rs"]
mod hosted_status_freshness;
pub(in crate::hosted) use hosted_status_freshness::*;

#[path = "generated/hosted_status_fact_scope.rs"]
mod hosted_status_fact_scope;
pub(in crate::hosted) use hosted_status_fact_scope::*;

#[path = "generated/hosted_status_fact_availability_impact.rs"]
mod hosted_status_fact_availability_impact;
pub(in crate::hosted) use hosted_status_fact_availability_impact::*;

#[path = "generated/hosted_status_fact_attention_impact.rs"]
mod hosted_status_fact_attention_impact;
pub(in crate::hosted) use hosted_status_fact_attention_impact::*;

#[path = "generated/hosted_workspace_ref.rs"]
mod hosted_workspace_ref;
pub(in crate::hosted) use hosted_workspace_ref::*;

#[path = "generated/hosted_refs_get_workspace_ref_request.rs"]
mod hosted_refs_get_workspace_ref_request;
pub(in crate::hosted) use hosted_refs_get_workspace_ref_request::*;

#[path = "generated/hosted_refs_create_workspace_ref_request.rs"]
mod hosted_refs_create_workspace_ref_request;
pub(in crate::hosted) use hosted_refs_create_workspace_ref_request::*;

#[path = "generated/hosted_refs_compare_and_swap_workspace_ref_request.rs"]
mod hosted_refs_compare_and_swap_workspace_ref_request;
pub(in crate::hosted) use hosted_refs_compare_and_swap_workspace_ref_request::*;

#[path = "generated/hosted_workspace_ref_or_null.rs"]
mod hosted_workspace_ref_or_null;
pub(in crate::hosted) use hosted_workspace_ref_or_null::*;

#[path = "generated/hosted_refs_compare_and_swap_workspace_ref_response.rs"]
mod hosted_refs_compare_and_swap_workspace_ref_response;
pub(in crate::hosted) use hosted_refs_compare_and_swap_workspace_ref_response::*;

#[path = "generated/hosted_compact_event.rs"]
mod hosted_compact_event;
pub(in crate::hosted) use hosted_compact_event::*;

#[path = "generated/hosted_events_list_compact_events_request.rs"]
mod hosted_events_list_compact_events_request;
pub(in crate::hosted) use hosted_events_list_compact_events_request::*;

#[path = "generated/hosted_events_list_compact_events_response.rs"]
mod hosted_events_list_compact_events_response;
pub(in crate::hosted) use hosted_events_list_compact_events_response::*;

#[path = "generated/hosted_status_action_reference.rs"]
mod hosted_status_action_reference;
pub(in crate::hosted) use hosted_status_action_reference::*;

#[path = "generated/hosted_status_fact.rs"]
mod hosted_status_fact;
pub(in crate::hosted) use hosted_status_fact::*;

#[path = "generated/hosted_sync_queue.rs"]
mod hosted_sync_queue;
pub(in crate::hosted) use hosted_sync_queue::*;

#[path = "generated/hosted_event_watermarks.rs"]
mod hosted_event_watermarks;
pub(in crate::hosted) use hosted_event_watermarks::*;

#[path = "generated/hosted_workspace_summary.rs"]
mod hosted_workspace_summary;
pub(in crate::hosted) use hosted_workspace_summary::*;

#[path = "generated/hosted_status_item.rs"]
mod hosted_status_item;
pub(in crate::hosted) use hosted_status_item::*;

#[path = "generated/hosted_limited_capability.rs"]
mod hosted_limited_capability;
pub(in crate::hosted) use hosted_limited_capability::*;

#[path = "generated/hosted_status_publish_workspace_status_request.rs"]
mod hosted_status_publish_workspace_status_request;
pub(in crate::hosted) use hosted_status_publish_workspace_status_request::*;

#[path = "generated/hosted_status_publish_workspace_status_response.rs"]
mod hosted_status_publish_workspace_status_response;
pub(in crate::hosted) use hosted_status_publish_workspace_status_response::*;

#[path = "generated/hosted_auth_register_account_session_request.rs"]
mod hosted_auth_register_account_session_request;
pub(in crate::hosted) use hosted_auth_register_account_session_request::*;

#[path = "generated/hosted_auth_register_account_session_response.rs"]
mod hosted_auth_register_account_session_response;
pub(in crate::hosted) use hosted_auth_register_account_session_response::*;

#[path = "generated/hosted_dashboard_provider_environment.rs"]
mod hosted_dashboard_provider_environment;
pub(in crate::hosted) use hosted_dashboard_provider_environment::*;

#[path = "generated/hosted_dashboard_workspace_role.rs"]
mod hosted_dashboard_workspace_role;
pub(in crate::hosted) use hosted_dashboard_workspace_role::*;

#[path = "generated/hosted_projection_repair_state.rs"]
mod hosted_projection_repair_state;
pub(in crate::hosted) use hosted_projection_repair_state::*;

#[path = "generated/hosted_dashboard_device_state.rs"]
mod hosted_dashboard_device_state;
pub(in crate::hosted) use hosted_dashboard_device_state::*;

#[path = "generated/hosted_dashboard_recovery_state.rs"]
mod hosted_dashboard_recovery_state;
pub(in crate::hosted) use hosted_dashboard_recovery_state::*;

#[path = "generated/hosted_dashboard_billing_plan_tier.rs"]
mod hosted_dashboard_billing_plan_tier;
pub(in crate::hosted) use hosted_dashboard_billing_plan_tier::*;

#[path = "generated/hosted_dashboard_billing_status.rs"]
mod hosted_dashboard_billing_status;
pub(in crate::hosted) use hosted_dashboard_billing_status::*;

#[path = "generated/hosted_dashboard_billing_message_key.rs"]
mod hosted_dashboard_billing_message_key;
pub(in crate::hosted) use hosted_dashboard_billing_message_key::*;

#[path = "generated/hosted_dashboard_billing_state.rs"]
mod hosted_dashboard_billing_state;
pub(in crate::hosted) use hosted_dashboard_billing_state::*;

#[path = "generated/hosted_dashboard_usage_freshness_state.rs"]
mod hosted_dashboard_usage_freshness_state;
pub(in crate::hosted) use hosted_dashboard_usage_freshness_state::*;

#[path = "generated/hosted_projection_metadata.rs"]
mod hosted_projection_metadata;
pub(in crate::hosted) use hosted_projection_metadata::*;

#[path = "generated/hosted_dashboard_account.rs"]
mod hosted_dashboard_account;
pub(in crate::hosted) use hosted_dashboard_account::*;

#[path = "generated/hosted_dashboard_workspace_membership.rs"]
mod hosted_dashboard_workspace_membership;
pub(in crate::hosted) use hosted_dashboard_workspace_membership::*;

#[path = "generated/hosted_dashboard_billing_portal.rs"]
mod hosted_dashboard_billing_portal;
pub(in crate::hosted) use hosted_dashboard_billing_portal::*;

#[path = "generated/hosted_dashboard_usage_freshness.rs"]
mod hosted_dashboard_usage_freshness;
pub(in crate::hosted) use hosted_dashboard_usage_freshness::*;

#[path = "generated/hosted_dashboard_billing_summary.rs"]
mod hosted_dashboard_billing_summary;
pub(in crate::hosted) use hosted_dashboard_billing_summary::*;

#[path = "generated/hosted_dashboard_get_dashboard_shell_request.rs"]
mod hosted_dashboard_get_dashboard_shell_request;
pub(in crate::hosted) use hosted_dashboard_get_dashboard_shell_request::*;

#[path = "generated/hosted_dashboard_get_dashboard_shell_response.rs"]
mod hosted_dashboard_get_dashboard_shell_response;
pub(in crate::hosted) use hosted_dashboard_get_dashboard_shell_response::*;

#[path = "generated/hosted_dashboard_status_aggregate.rs"]
mod hosted_dashboard_status_aggregate;
pub(in crate::hosted) use hosted_dashboard_status_aggregate::*;

#[path = "generated/hosted_dashboard_device_summary.rs"]
mod hosted_dashboard_device_summary;
pub(in crate::hosted) use hosted_dashboard_device_summary::*;

#[path = "generated/hosted_dashboard_recovery_summary.rs"]
mod hosted_dashboard_recovery_summary;
pub(in crate::hosted) use hosted_dashboard_recovery_summary::*;

#[path = "generated/hosted_dashboard_workspace_ref.rs"]
mod hosted_dashboard_workspace_ref;
pub(in crate::hosted) use hosted_dashboard_workspace_ref::*;

#[path = "generated/hosted_dashboard_get_workspace_dashboard_current_request.rs"]
mod hosted_dashboard_get_workspace_dashboard_current_request;
pub(in crate::hosted) use hosted_dashboard_get_workspace_dashboard_current_request::*;

#[path = "generated/hosted_dashboard_get_workspace_dashboard_current_response.rs"]
mod hosted_dashboard_get_workspace_dashboard_current_response;
pub(in crate::hosted) use hosted_dashboard_get_workspace_dashboard_current_response::*;

#[path = "generated/hosted_dashboard_device_row.rs"]
mod hosted_dashboard_device_row;
pub(in crate::hosted) use hosted_dashboard_device_row::*;

#[path = "generated/hosted_dashboard_list_dashboard_devices_request.rs"]
mod hosted_dashboard_list_dashboard_devices_request;
pub(in crate::hosted) use hosted_dashboard_list_dashboard_devices_request::*;

#[path = "generated/hosted_dashboard_list_dashboard_devices_response.rs"]
mod hosted_dashboard_list_dashboard_devices_response;
pub(in crate::hosted) use hosted_dashboard_list_dashboard_devices_response::*;

#[path = "generated/hosted_dashboard_recovery_row.rs"]
mod hosted_dashboard_recovery_row;
pub(in crate::hosted) use hosted_dashboard_recovery_row::*;

#[path = "generated/hosted_dashboard_list_dashboard_recovery_envelopes_request.rs"]
mod hosted_dashboard_list_dashboard_recovery_envelopes_request;
pub(in crate::hosted) use hosted_dashboard_list_dashboard_recovery_envelopes_request::*;

#[path = "generated/hosted_dashboard_list_dashboard_recovery_envelopes_response.rs"]
mod hosted_dashboard_list_dashboard_recovery_envelopes_response;
pub(in crate::hosted) use hosted_dashboard_list_dashboard_recovery_envelopes_response::*;
